/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Edixon Gonzalez
 */
public class vistaJuegoPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form vistaJuegoPreguntas
     */
    public vistaJuegoPreguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonIniciarSesion = new javax.swing.JLabel();
        jTurnoJugador = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jOpcionA = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jOpcionB = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jOpcionC = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jOpcionD = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jImagen1 = new javax.swing.JPanel();
        jImagen2 = new javax.swing.JPanel();
        jPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(255, 242, 223));
        jFondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setBackground(new java.awt.Color(78, 95, 23));
        Banner.setPreferredSize(new java.awt.Dimension(1280, 160));
        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(213, 223, 181));
        jLabel5.setText("CABINAS AZULES");
        Banner.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 436, 36));

        jLabel14.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(213, 223, 181));
        jLabel14.setText("¡Bienvenidos al quiz!");
        Banner.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 436, 36));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/glasses.png"))); // NOI18N
        Banner.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonIniciarSesion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButtonIniciarSesion.setForeground(new java.awt.Color(242, 242, 242));
        jButtonIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logout.png"))); // NOI18N
        jButtonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIniciarSesionMouseClicked(evt);
            }
        });
        Banner.add(jButtonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 50, -1, -1));

        jFondo.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTurnoJugador.setBackground(new java.awt.Color(78, 95, 23));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(213, 223, 181));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Jugador, ¡es tu turno!");

        javax.swing.GroupLayout jTurnoJugadorLayout = new javax.swing.GroupLayout(jTurnoJugador);
        jTurnoJugador.setLayout(jTurnoJugadorLayout);
        jTurnoJugadorLayout.setHorizontalGroup(
            jTurnoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTurnoJugadorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jTurnoJugadorLayout.setVerticalGroup(
            jTurnoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTurnoJugadorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jFondo.add(jTurnoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 440, 70));

        jOpcionA.setBackground(new java.awt.Color(255, 87, 87));

        jLabel10.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("OPCION A");

        javax.swing.GroupLayout jOpcionALayout = new javax.swing.GroupLayout(jOpcionA);
        jOpcionA.setLayout(jOpcionALayout);
        jOpcionALayout.setHorizontalGroup(
            jOpcionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOpcionALayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jOpcionALayout.setVerticalGroup(
            jOpcionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionALayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jFondo.add(jOpcionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 510, -1));

        jOpcionB.setBackground(new java.awt.Color(140, 82, 255));
        jOpcionB.setPreferredSize(new java.awt.Dimension(510, 92));

        jLabel9.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("OPCION B");

        javax.swing.GroupLayout jOpcionBLayout = new javax.swing.GroupLayout(jOpcionB);
        jOpcionB.setLayout(jOpcionBLayout);
        jOpcionBLayout.setHorizontalGroup(
            jOpcionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOpcionBLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jOpcionBLayout.setVerticalGroup(
            jOpcionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionBLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jFondo.add(jOpcionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        jOpcionC.setBackground(new java.awt.Color(126, 217, 87));
        jOpcionC.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel11.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("OPCION C");

        javax.swing.GroupLayout jOpcionCLayout = new javax.swing.GroupLayout(jOpcionC);
        jOpcionC.setLayout(jOpcionCLayout);
        jOpcionCLayout.setHorizontalGroup(
            jOpcionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOpcionCLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jOpcionCLayout.setVerticalGroup(
            jOpcionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionCLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jFondo.add(jOpcionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 510, -1));

        jOpcionD.setBackground(new java.awt.Color(255, 189, 89));
        jOpcionD.setPreferredSize(new java.awt.Dimension(510, 92));

        jLabel12.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("OPCION D");

        javax.swing.GroupLayout jOpcionDLayout = new javax.swing.GroupLayout(jOpcionD);
        jOpcionD.setLayout(jOpcionDLayout);
        jOpcionDLayout.setHorizontalGroup(
            jOpcionDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOpcionDLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jOpcionDLayout.setVerticalGroup(
            jOpcionDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionDLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jFondo.add(jOpcionD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        jImagen1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jImagen1Layout = new javax.swing.GroupLayout(jImagen1);
        jImagen1.setLayout(jImagen1Layout);
        jImagen1Layout.setHorizontalGroup(
            jImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        jImagen1Layout.setVerticalGroup(
            jImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jFondo.add(jImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 230));

        jImagen2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jImagen2Layout = new javax.swing.GroupLayout(jImagen2);
        jImagen2.setLayout(jImagen2Layout);
        jImagen2Layout.setHorizontalGroup(
            jImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        jImagen2Layout.setVerticalGroup(
            jImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jFondo.add(jImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, -1, 230));

        jPregunta.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPregunta.setForeground(new java.awt.Color(123, 58, 0));
        jPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPregunta.setText("Pregunta sacada de la base de datos");
        jFondo.add(jPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 660, 88));

        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIniciarSesionMouseClicked
        this.dispose();
        controladora.vistaManagement.loadStart();
    }//GEN-LAST:event_jButtonIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaJuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaJuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaJuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaJuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaJuegoPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JLabel jButtonIniciarSesion;
    private javax.swing.JPanel jFondo;
    private javax.swing.JPanel jImagen1;
    private javax.swing.JPanel jImagen2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jOpcionA;
    private javax.swing.JPanel jOpcionB;
    private javax.swing.JPanel jOpcionC;
    private javax.swing.JPanel jOpcionD;
    private javax.swing.JLabel jPregunta;
    private javax.swing.JPanel jTurnoJugador;
    // End of variables declaration//GEN-END:variables
}
