/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author umaru
 */
public class interfazAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DetalleObra
     */
    public interfazAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneFondo = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        pageName = new javax.swing.JLabel();
        estado = new javax.swing.JPanel();
        activo = new javax.swing.JLabel();
        inactivo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pestanas = new javax.swing.JTabbedPane();
        jTabPreguntas = new javax.swing.JPanel();
        jScrollPanePreguntas = new javax.swing.JScrollPane();
        jTablePreguntas = new javax.swing.JTable();
        jButtonAgregarPregunta = new javax.swing.JButton();
        jBuscadorDePreg = new javax.swing.JTextField();
        jBotonDeBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabMateriales = new javax.swing.JPanel();
        jTabPresupuesto = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menu1 = new javax.swing.JPanel();
        catalogo = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        materiales = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        Presupuesto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPaneFondo.setBackground(new java.awt.Color(153, 153, 153));
        jPaneFondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPaneFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSuperior.setBackground(new java.awt.Color(176, 176, 176));
        panelSuperior.setMaximumSize(new java.awt.Dimension(1010, 100));
        panelSuperior.setMinimumSize(new java.awt.Dimension(1010, 100));
        panelSuperior.setPreferredSize(new java.awt.Dimension(1010, 100));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pageName.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        pageName.setForeground(new java.awt.Color(255, 255, 255));
        pageName.setText("NOMBRE DE PÁGINA");
        panelSuperior.add(pageName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 597, 53));

        estado.setBackground(new java.awt.Color(120, 120, 120));
        estado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        activo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        activo.setForeground(new java.awt.Color(255, 255, 255));
        activo.setText("Activo");
        estado.add(activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 61, -1));

        inactivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        inactivo.setForeground(new java.awt.Color(255, 255, 255));
        inactivo.setText("Inactivo");
        estado.add(inactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 70, -1));

        panelSuperior.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 121, 770, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vista de administrador");
        panelSuperior.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jPaneFondo.add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 160));

        pestanas.setBackground(new java.awt.Color(204, 204, 204));
        pestanas.setForeground(new java.awt.Color(204, 204, 204));

        jTabPreguntas.setBackground(new java.awt.Color(255, 255, 255));
        jTabPreguntas.setMaximumSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setMinimumSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setPreferredSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanePreguntas.setViewportView(jTablePreguntas);

        jTabPreguntas.add(jScrollPanePreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 137, 960, 415));

        jButtonAgregarPregunta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButtonAgregarPregunta.setText("Agregar pregunta");
        jButtonAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPreguntaActionPerformed(evt);
            }
        });
        jTabPreguntas.add(jButtonAgregarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 47, 162, 48));

        jBuscadorDePreg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBuscadorDePreg.setForeground(new java.awt.Color(90, 90, 90));
        jBuscadorDePreg.setText("Buscar...");
        jBuscadorDePreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuscadorDePregMouseClicked(evt);
            }
        });
        jBuscadorDePreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscadorDePregActionPerformed(evt);
            }
        });
        jTabPreguntas.add(jBuscadorDePreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 47, 589, 50));

        jBotonDeBuscar.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setText("lupa");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jBotonDeBuscarLayout = new javax.swing.GroupLayout(jBotonDeBuscar);
        jBotonDeBuscar.setLayout(jBotonDeBuscarLayout);
        jBotonDeBuscarLayout.setHorizontalGroup(
            jBotonDeBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotonDeBuscarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBotonDeBuscarLayout.setVerticalGroup(
            jBotonDeBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBotonDeBuscarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabPreguntas.add(jBotonDeBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 47, -1, -1));

        pestanas.addTab("tab1", jTabPreguntas);

        jTabMateriales.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jTabMaterialesLayout = new javax.swing.GroupLayout(jTabMateriales);
        jTabMateriales.setLayout(jTabMaterialesLayout);
        jTabMaterialesLayout.setHorizontalGroup(
            jTabMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jTabMaterialesLayout.setVerticalGroup(
            jTabMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        pestanas.addTab("tab1", jTabMateriales);

        jPanel18.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Por Desarrollar ");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(613, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jTabPresupuestoLayout = new javax.swing.GroupLayout(jTabPresupuesto);
        jTabPresupuesto.setLayout(jTabPresupuestoLayout);
        jTabPresupuestoLayout.setHorizontalGroup(
            jTabPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTabPresupuestoLayout.setVerticalGroup(
            jTabPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pestanas.addTab("tab3", jTabPresupuesto);

        jPaneFondo.add(pestanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 1010, 620));
        pestanas.getAccessibleContext().setAccessibleName("");
        pestanas.getAccessibleContext().setAccessibleDescription("");

        menu1.setBackground(new java.awt.Color(120, 120, 120));
        menu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu1MouseMoved(evt);
            }
        });
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        catalogo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        catalogo.setForeground(new java.awt.Color(255, 255, 255));
        catalogo.setText("Preguntas");

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(catalogo)
                .addGap(56, 56, 56))
        );

        jPaneFondo.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 180));

        menu2.setBackground(new java.awt.Color(120, 120, 120));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        materiales.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        materiales.setForeground(new java.awt.Color(255, 255, 255));
        materiales.setText("Materiales");

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(materiales)
                .addGap(51, 51, 51))
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(materiales)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPaneFondo.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 200));

        menu3.setBackground(new java.awt.Color(120, 120, 120));
        menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu3MouseClicked(evt);
            }
        });

        Presupuesto.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Presupuesto.setForeground(new java.awt.Color(255, 255, 255));
        Presupuesto.setText("Presupuesto");

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Presupuesto)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        menu3Layout.setVerticalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Presupuesto)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPaneFondo.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 535, 270, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        pestanas.setSelectedIndex(0);
        Object[] header = new Object[]{"Nro", "Pregunta", "% de acierto"};
        DefaultTableModel model = new DefaultTableModel(header, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        for(controladora.Pregunta pregunta : recursos.globalAccess.listaDePreguntas){
            model.addRow(new Object[]{recursos.globalAccess.listaDePreguntas.indexOf(pregunta), pregunta.getEnunciado(), pregunta.getPorcentajedeacierto()});
        }
        jTablePreguntas.setModel(model);
        jScrollPanePreguntas.setVisible(true);
        jTablePreguntas.setVisible(true);
    }//GEN-LAST:event_menu1MouseClicked

    private void menu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseMoved
        
    }//GEN-LAST:event_menu1MouseMoved

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        pestanas.setSelectedIndex(1);
    }//GEN-LAST:event_menu2MouseClicked

    private void menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3MouseClicked
        pestanas.setSelectedIndex(2);
    }//GEN-LAST:event_menu3MouseClicked

    private void jButtonAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPreguntaActionPerformed

    private void jBuscadorDePregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscadorDePregActionPerformed
        jBuscadorDePreg.setText("");
    }//GEN-LAST:event_jBuscadorDePregActionPerformed

    private void jBuscadorDePregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscadorDePregMouseClicked
        jBuscadorDePreg.setText("");
    }//GEN-LAST:event_jBuscadorDePregMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Presupuesto;
    private javax.swing.JLabel activo;
    private javax.swing.JLabel catalogo;
    private javax.swing.JPanel estado;
    private javax.swing.JLabel inactivo;
    private javax.swing.JPanel jBotonDeBuscar;
    private javax.swing.JTextField jBuscadorDePreg;
    private javax.swing.JButton jButtonAgregarPregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneFondo;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPanePreguntas;
    private javax.swing.JPanel jTabMateriales;
    private javax.swing.JPanel jTabPreguntas;
    private javax.swing.JPanel jTabPresupuesto;
    private javax.swing.JTable jTablePreguntas;
    private javax.swing.JLabel materiales;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JLabel pageName;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTabbedPane pestanas;
    // End of variables declaration//GEN-END:variables
}
