/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import javax.swing.table.JTableHeader;
import java.awt.Font;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.JOptionPane;
import modelo.Pregunta;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


/**
 *
 * @author umaru
 */
public class InterfazAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DetalleObra
     */
    public InterfazAdmin() {
        initComponents();
        
        pestanas.setSelectedIndex(0);
        jTablePreguntas.setModel(controladora.vistaManagement.setModeloTablaPreguntas(false, ""));
        JTableHeader tableHeader = jTablePreguntas.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);


        jTablePreguntas.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePreguntas.getColumnModel().getColumn(1).setPreferredWidth(800);
        jTablePreguntas.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTablePreguntas.setAutoResizeMode(jTablePreguntas.AUTO_RESIZE_LAST_COLUMN);
        jTablePreguntas.setRowHeight(20);
        jScrollPanePreguntas.setVisible(true);
        jTablePreguntas.setVisible(true);


        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTablePreguntas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOpcionCorrecta = new javax.swing.ButtonGroup();
        jPaneFondo = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonAgregarPregunta1 = new javax.swing.JButton();
        pestanas = new javax.swing.JTabbedPane();
        jTabPreguntas = new javax.swing.JPanel();
        jScrollPanePreguntas = new javax.swing.JScrollPane();
        jTablePreguntas = new javax.swing.JTable();
        jButtonAgregarPregunta = new javax.swing.JButton();
        jBuscadorDePreg = new javax.swing.JTextField();
        jBotonDeBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabMateriales = new javax.swing.JPanel();
        jTabPresupuesto = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jInstruccion = new javax.swing.JLabel();
        jSeleccionarMaterial1 = new javax.swing.JComboBox<>();
        jSeleccionarMaterial2 = new javax.swing.JComboBox<>();
        jSeleccionarMaterial3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jCalcularPresupuesto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabEditarPregunta = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jPanelGuide = new javax.swing.JPanel();
        Pregunta = new javax.swing.JTextField();
        Opcion1 = new javax.swing.JTextField();
        Opcion4 = new javax.swing.JTextField();
        Opcion3 = new javax.swing.JTextField();
        Opcion2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanelButtonGuide = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        cargarImagen = new javax.swing.JButton();
        guardarCambios = new javax.swing.JButton();
        editingCheck = new javax.swing.JCheckBox();
        menu1 = new javax.swing.JPanel();
        catalogo = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        materiales = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        Presupuesto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPaneFondo.setBackground(new java.awt.Color(153, 153, 153));
        jPaneFondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPaneFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setBackground(new java.awt.Color(78, 95, 23));
        Banner.setPreferredSize(new java.awt.Dimension(1280, 160));
        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(213, 223, 181));
        jLabel4.setText("CABINAS AZULES");
        Banner.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 436, 36));

        jLabel6.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(213, 223, 181));
        jLabel6.setText("Inicio de sesion");
        Banner.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 436, 36));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/glasses.png"))); // NOI18N
        Banner.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonAgregarPregunta1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonAgregarPregunta1.setForeground(new java.awt.Color(123, 58, 0));
        jButtonAgregarPregunta1.setText("Volver al inicio");
        jButtonAgregarPregunta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarPregunta1MouseClicked(evt);
            }
        });
        jButtonAgregarPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPregunta1ActionPerformed(evt);
            }
        });
        Banner.add(jButtonAgregarPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, 170, 48));

        jPaneFondo.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pestanas.setBackground(new java.awt.Color(204, 204, 204));
        pestanas.setForeground(new java.awt.Color(204, 204, 204));

        jTabPreguntas.setBackground(new java.awt.Color(255, 242, 223));
        jTabPreguntas.setMaximumSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setMinimumSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setPreferredSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePreguntas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTablePreguntas.setForeground(new java.awt.Color(123, 58, 0));
        jTablePreguntas.setRowHeight(50);
        jTablePreguntas.setRowSelectionAllowed(false);
        jTablePreguntas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablePreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTablePreguntasMousePressed(evt);
            }
        });
        jScrollPanePreguntas.setViewportView(jTablePreguntas);

        jTabPreguntas.add(jScrollPanePreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 137, 960, 415));

        jButtonAgregarPregunta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonAgregarPregunta.setForeground(new java.awt.Color(123, 58, 0));
        jButtonAgregarPregunta.setText("Agregar pregunta");
        jButtonAgregarPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarPreguntaMouseClicked(evt);
            }
        });
        jButtonAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPreguntaActionPerformed(evt);
            }
        });
        jTabPreguntas.add(jButtonAgregarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 47, 170, 48));

        jBuscadorDePreg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBuscadorDePreg.setForeground(new java.awt.Color(163, 98, 40));
        jBuscadorDePreg.setText("Buscar...");
        jBuscadorDePreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuscadorDePregMouseClicked(evt);
            }
        });
        jBuscadorDePreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscadorDePregActionPerformed(evt);
            }
        });
        jBuscadorDePreg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBuscadorDePregKeyReleased(evt);
            }
        });
        jTabPreguntas.add(jBuscadorDePreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 47, 589, 50));

        jBotonDeBuscar.setBackground(new java.awt.Color(78, 95, 23));
        jBotonDeBuscar.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/magnifier.png"))); // NOI18N
        jLabel1.setIconTextGap(0);

        javax.swing.GroupLayout jBotonDeBuscarLayout = new javax.swing.GroupLayout(jBotonDeBuscar);
        jBotonDeBuscar.setLayout(jBotonDeBuscarLayout);
        jBotonDeBuscarLayout.setHorizontalGroup(
            jBotonDeBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBotonDeBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jBotonDeBuscarLayout.setVerticalGroup(
            jBotonDeBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBotonDeBuscarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabPreguntas.add(jBotonDeBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 47, -1, -1));

        pestanas.addTab("tab1", jTabPreguntas);

        jTabMateriales.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jTabMaterialesLayout = new javax.swing.GroupLayout(jTabMateriales);
        jTabMateriales.setLayout(jTabMaterialesLayout);
        jTabMaterialesLayout.setHorizontalGroup(
            jTabMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jTabMaterialesLayout.setVerticalGroup(
            jTabMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        pestanas.addTab("tab1", jTabMateriales);

        jPanel18.setBackground(new java.awt.Color(255, 242, 223));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInstruccion.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jInstruccion.setForeground(new java.awt.Color(123, 58, 0));
        jInstruccion.setText("Seleccione los materiales a utilizar");
        jPanel18.add(jInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jSeleccionarMaterial1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jSeleccionarMaterial1.setForeground(new java.awt.Color(123, 58, 0));
        jSeleccionarMaterial1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel18.add(jSeleccionarMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 580, 50));

        jSeleccionarMaterial2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jSeleccionarMaterial2.setForeground(new java.awt.Color(123, 58, 0));
        jSeleccionarMaterial2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jSeleccionarMaterial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeleccionarMaterial2ActionPerformed(evt);
            }
        });
        jPanel18.add(jSeleccionarMaterial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 580, 50));

        jSeleccionarMaterial3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jSeleccionarMaterial3.setForeground(new java.awt.Color(123, 58, 0));
        jSeleccionarMaterial3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel18.add(jSeleccionarMaterial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 580, 50));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(123, 58, 0));
        jTextField1.setText(". . .");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel18.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 580, 50));

        jCalcularPresupuesto.setBackground(new java.awt.Color(78, 95, 23));
        jCalcularPresupuesto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCalcularPresupuesto.setForeground(new java.awt.Color(213, 223, 181));
        jCalcularPresupuesto.setText("Calcular presupuesto");
        jPanel18.add(jCalcularPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 250, 50));

        jPanel1.setBackground(new java.awt.Color(123, 58, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 242, 223));
        jLabel2.setText("Presupuesto aquí...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel18.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 250, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 58, 0));
        jLabel3.setText("Paredes");
        jPanel18.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(123, 58, 0));
        jLabel5.setText("Costos adicionales");
        jPanel18.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(123, 58, 0));
        jLabel7.setText("Techo");
        jPanel18.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(123, 58, 0));
        jLabel8.setText("Suelo");
        jPanel18.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        javax.swing.GroupLayout jTabPresupuestoLayout = new javax.swing.GroupLayout(jTabPresupuesto);
        jTabPresupuesto.setLayout(jTabPresupuestoLayout);
        jTabPresupuestoLayout.setHorizontalGroup(
            jTabPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTabPresupuestoLayout.setVerticalGroup(
            jTabPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pestanas.addTab("tab3", jTabPresupuesto);

        jTabEditarPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabEditarPreguntaMouseClicked(evt);
            }
        });

        Background.setBackground(new java.awt.Color(255, 242, 223));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setFocusable(false);
        imagen.setMaximumSize(new java.awt.Dimension(200, 290));
        imagen.setMinimumSize(new java.awt.Dimension(200, 290));
        imagen.setOpaque(true);
        imagen.setPreferredSize(new java.awt.Dimension(200, 290));
        Background.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 290));

        jPanelGuide.setBackground(new java.awt.Color(255, 242, 223));

        Pregunta.setToolTipText("Ingresar enunciado de pregunta");
        Pregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreguntaActionPerformed(evt);
            }
        });

        Opcion1.setToolTipText("Ingresar opcion 1");
        Opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion1ActionPerformed(evt);
            }
        });

        Opcion4.setToolTipText("Ingresar opcion 4");
        Opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion4ActionPerformed(evt);
            }
        });

        Opcion3.setToolTipText("Ingresar opcion 3");
        Opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion3ActionPerformed(evt);
            }
        });

        Opcion2.setToolTipText("Ingresar opcion 2");
        Opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion2ActionPerformed(evt);
            }
        });

        buttonGroupOpcionCorrecta.add(jRadioButton1);
        jRadioButton1.setText("Opcion 1:");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroupOpcionCorrecta.add(jRadioButton2);
        jRadioButton2.setText("Opcion 2:");

        buttonGroupOpcionCorrecta.add(jRadioButton3);
        jRadioButton3.setText("Opcion 3:");

        buttonGroupOpcionCorrecta.add(jRadioButton4);
        jRadioButton4.setText("Opcion 4:");

        javax.swing.GroupLayout jPanelGuideLayout = new javax.swing.GroupLayout(jPanelGuide);
        jPanelGuide.setLayout(jPanelGuideLayout);
        jPanelGuideLayout.setHorizontalGroup(
            jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuideLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelGuideLayout.createSequentialGroup()
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelGuideLayout.createSequentialGroup()
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(Opcion1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelGuideLayout.createSequentialGroup()
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(Opcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelGuideLayout.createSequentialGroup()
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanelGuideLayout.setVerticalGroup(
            jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuideLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        Background.add(jPanelGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 740, 390));

        jPanelButtonGuide.setBackground(new java.awt.Color(255, 242, 223));

        volver.setText("Atrás");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        cargarImagen.setText("Cargar Imagen");
        cargarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarImagenMouseClicked(evt);
            }
        });
        cargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImagenActionPerformed(evt);
            }
        });

        guardarCambios.setText("Guardar");
        guardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarCambiosMouseClicked(evt);
            }
        });
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonGuideLayout = new javax.swing.GroupLayout(jPanelButtonGuide);
        jPanelButtonGuide.setLayout(jPanelButtonGuideLayout);
        jPanelButtonGuideLayout.setHorizontalGroup(
            jPanelButtonGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonGuideLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addGroup(jPanelButtonGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelButtonGuideLayout.createSequentialGroup()
                        .addComponent(guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonGuideLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelButtonGuideLayout.setVerticalGroup(
            jPanelButtonGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonGuideLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelButtonGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Background.add(jPanelButtonGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1000, 180));

        javax.swing.GroupLayout jTabEditarPreguntaLayout = new javax.swing.GroupLayout(jTabEditarPregunta);
        jTabEditarPregunta.setLayout(jTabEditarPreguntaLayout);
        jTabEditarPreguntaLayout.setHorizontalGroup(
            jTabEditarPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTabEditarPreguntaLayout.setVerticalGroup(
            jTabEditarPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pestanas.addTab("tab4", jTabEditarPregunta);

        editingCheck.setText("Editando");
        editingCheck.setToolTipText("");
        editingCheck.setFocusable(false);
        pestanas.addTab("tab5", editingCheck);

        jPaneFondo.add(pestanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 1010, 620));
        pestanas.getAccessibleContext().setAccessibleName("");
        pestanas.getAccessibleContext().setAccessibleDescription("");

        menu1.setBackground(new java.awt.Color(213, 223, 181));
        menu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu1MouseMoved(evt);
            }
        });
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        catalogo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        catalogo.setForeground(new java.awt.Color(78, 95, 23));
        catalogo.setText("Preguntas");

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(catalogo)
                .addGap(56, 56, 56))
        );

        jPaneFondo.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 180));

        menu2.setBackground(new java.awt.Color(213, 223, 181));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        materiales.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        materiales.setForeground(new java.awt.Color(78, 95, 23));
        materiales.setText("Materiales");

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(materiales)
                .addGap(51, 51, 51))
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(materiales)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPaneFondo.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 200));

        menu3.setBackground(new java.awt.Color(213, 223, 181));
        menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu3MouseClicked(evt);
            }
        });

        Presupuesto.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Presupuesto.setForeground(new java.awt.Color(78, 95, 23));
        Presupuesto.setText("Presupuesto");

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Presupuesto)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        menu3Layout.setVerticalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Presupuesto)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPaneFondo.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 535, 270, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        pestanas.setSelectedIndex(0);
        jTablePreguntas.setModel(controladora.vistaManagement.setModeloTablaPreguntas(false,""));
        JTableHeader tableHeader = jTablePreguntas.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);
        
        
        jTablePreguntas.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePreguntas.getColumnModel().getColumn(1).setPreferredWidth(800);
        jTablePreguntas.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTablePreguntas.setAutoResizeMode(jTablePreguntas.AUTO_RESIZE_LAST_COLUMN);
        jTablePreguntas.setRowHeight(20);
        jScrollPanePreguntas.setVisible(true);
        jTablePreguntas.setVisible(true);
        
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTablePreguntas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        
    }//GEN-LAST:event_menu1MouseClicked

    private void menu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseMoved
        
    }//GEN-LAST:event_menu1MouseMoved

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        pestanas.setSelectedIndex(1);
    }//GEN-LAST:event_menu2MouseClicked

    private void menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3MouseClicked
        pestanas.setSelectedIndex(2);
    }//GEN-LAST:event_menu3MouseClicked

    private void jButtonAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntaActionPerformed
        // POPUP agregar pregunta y definir opciones
    }//GEN-LAST:event_jButtonAgregarPreguntaActionPerformed

    private void jBuscadorDePregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscadorDePregActionPerformed
        jBuscadorDePreg.setText("");
    }//GEN-LAST:event_jBuscadorDePregActionPerformed

    private void jBuscadorDePregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscadorDePregMouseClicked
        jBuscadorDePreg.setText("");
    }//GEN-LAST:event_jBuscadorDePregMouseClicked

    private void jButtonAgregarPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPregunta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPregunta1ActionPerformed

    private void jButtonAgregarPregunta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarPregunta1MouseClicked
        this.dispose();
        controladora.vistaManagement.loadStart();
    }//GEN-LAST:event_jButtonAgregarPregunta1MouseClicked

    private void jSeleccionarMaterial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeleccionarMaterial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeleccionarMaterial2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonAgregarPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntaMouseClicked
        pestanas.setSelectedIndex(3);
        editingCheck.setSelected(false);
    }//GEN-LAST:event_jButtonAgregarPreguntaMouseClicked

    private void Opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion1ActionPerformed

    private void PreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreguntaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        
    }//GEN-LAST:event_volverActionPerformed

    private void cargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarImagenActionPerformed

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarCambiosActionPerformed

    private void Opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion2ActionPerformed

    private void Opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion3ActionPerformed

    private void Opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void guardarCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarCambiosMouseClicked
        // GUARDAR CAMBIOS
        String opc1, opc2, opc3, opc4, enunciado = "";
        int respuestaCorrecta = 0;
       
        opc1 = (Opcion1.getText()!=null) ? Opcion1.getText() : " " ;
        opc2 = (Opcion2.getText()!=null) ? Opcion2.getText() : " " ;
        opc3 = (Opcion3.getText()!=null) ? Opcion3.getText() : " " ;
        opc4 = (Opcion4.getText()!=null) ? Opcion4.getText() : " " ;
        
        
        String[] opciones = new String[]{opc1,opc2,opc3,opc4};
        enunciado = Pregunta.getText();
        
        if(jRadioButton1.isSelected()){respuestaCorrecta = 1;} 
        if(jRadioButton2.isSelected()){respuestaCorrecta = 2;}
        if(jRadioButton3.isSelected()){respuestaCorrecta = 3;}
        if(jRadioButton4.isSelected()){respuestaCorrecta = 4;}
        
        //Entra aqui si el usuario no ha ingresado ninguna opcion como la correcta
        if(respuestaCorrecta == 0){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna opcion como la correcta.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{ 
            // Entra aqui si la pregunta paso los requerimientos para ser agregada al sistema.
            if(!editingCheck.isSelected()){
                // AGREGANDO PREGUNTA
                Pregunta P1  = new Pregunta(enunciado,opciones,respuestaCorrecta,modelo.globalAccess.imagePath.get(0));
                modelo.globalAccess.listaDePreguntas.add(P1);
            }else{
                // EDITANDO PREGUNTA
                int location=jTablePreguntas.getSelectedRow();
                modelo.globalAccess.listaDePreguntas.get(location).setEnunciado(enunciado);
                modelo.globalAccess.listaDePreguntas.get(location).setOpciones(opciones);
                modelo.globalAccess.listaDePreguntas.get(location).setRespuestacorrecta(respuestaCorrecta);
                if(!modelo.globalAccess.imagePath.get(0).isEmpty()){
                    modelo.globalAccess.listaDePreguntas.get(location).setImagePath(modelo.globalAccess.imagePath.get(0));
                }
                
            }
            
            //RESETEAR LOS TEXTOS Y OPCIONES
            opciones = null;
            Opcion1.setText("");
            Opcion2.setText("");
            Opcion3.setText("");
            Opcion4.setText("");
            Pregunta.setText("");
            buttonGroupOpcionCorrecta.clearSelection();
            imagen.setIcon(null);
            modelo.globalAccess.imagePath.set(0,"");
            
            // LIMPIAR EL ARRAY CON LA IMAGEN modelo.globalAccess.imagePath.add(file_path);
            
            pestanas.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Pregunta guardada exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            
            //REFRESCAR LA TABLA
            jTablePreguntas.setModel(controladora.vistaManagement.setModeloTablaPreguntas(false, ""));
            JTableHeader tableHeader = jTablePreguntas.getTableHeader();
            Font headerFont = new Font("Arial", Font.BOLD, 18);
            float[] hsbColor = new float[3];
            Color.RGBtoHSB(163, 58, 0, hsbColor);
            tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
            tableHeader.setFont(headerFont);


            jTablePreguntas.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTablePreguntas.getColumnModel().getColumn(1).setPreferredWidth(800);
            jTablePreguntas.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTablePreguntas.setAutoResizeMode(jTablePreguntas.AUTO_RESIZE_LAST_COLUMN);
            jTablePreguntas.setRowHeight(20);
            jScrollPanePreguntas.setVisible(true);
            jTablePreguntas.setVisible(true);


            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            jTablePreguntas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_guardarCambiosMouseClicked

    private void jTabEditarPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabEditarPreguntaMouseClicked

    }//GEN-LAST:event_jTabEditarPreguntaMouseClicked

    private void cargarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarImagenMouseClicked
        JFileChooser elegirImagen = new JFileChooser();
        
        int res = elegirImagen.showSaveDialog(null);
        
        if(res == JFileChooser.APPROVE_OPTION){
            String file_path = elegirImagen.getSelectedFile().getAbsolutePath();
            
            modelo.globalAccess.imagePath.set(0,file_path);
            
            ImageIcon icon = new ImageIcon(file_path);
            
            //hacer que la imagen haga resize para el recuadro
            Image imageToResize = icon.getImage();
            Image resizedImage = imageToResize.getScaledInstance(imagen.getWidth(),imagen.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon resizedIcon = new ImageIcon(resizedImage);
            
            // Set el icono dentro del label
            imagen.setIcon(resizedIcon);
        }
            
    }//GEN-LAST:event_cargarImagenMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        Opcion1.setText("");
        Opcion2.setText("");
        Opcion3.setText("");
        Opcion4.setText("");
        Pregunta.setText("");
        buttonGroupOpcionCorrecta.clearSelection();
        imagen.setIcon(null);
        editingCheck.setSelected(false); 
        pestanas.setSelectedIndex(0);
    }//GEN-LAST:event_volverMouseClicked

    private void jTablePreguntasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePreguntasMousePressed

        pestanas.setSelectedIndex(3); 
        
        //Numero de columna a la que le dieron click/INDICE DEL OBJETO EN EL ARRAYLIST
        int location=jTablePreguntas.getSelectedRow();
        
        // Mostrar las opciones actuales de la pregunta anterior
        Opcion1.setText(modelo.globalAccess.listaDePreguntas.get(location).getOpciones()[0]);
        Opcion2.setText(modelo.globalAccess.listaDePreguntas.get(location).getOpciones()[1]);
        Opcion3.setText(modelo.globalAccess.listaDePreguntas.get(location).getOpciones()[2]);
        Opcion4.setText(modelo.globalAccess.listaDePreguntas.get(location).getOpciones()[3]);
        Pregunta.setText(modelo.globalAccess.listaDePreguntas.get(location).getEnunciado());
        
        ImageIcon icon = new ImageIcon(modelo.globalAccess.listaDePreguntas.get(location).getImagePath());
        //hacer que la imagen haga resize para el recuadro
        Image imageToResize = icon.getImage();
        Image resizedImage = imageToResize.getScaledInstance(imagen.getWidth(),imagen.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizedImage);

        // Set el icono dentro del label
        imagen.setIcon(resizedIcon);
        
        // Set el boton que indica cual es la correcta
        switch(modelo.globalAccess.listaDePreguntas.get(location).getRespuestacorrecta()){
            case 1:
                jRadioButton1.setSelected(true);
                break;
            case 2:
                jRadioButton2.setSelected(true);
                break;
            case 3:
                jRadioButton3.setSelected(true);
                break;
            case 4:
                jRadioButton4.setSelected(true);
                break;
        }
    
        
        //para indicarle que estamos editando una pregunta que ya existe
        editingCheck.setSelected(true); 
    }//GEN-LAST:event_jTablePreguntasMousePressed

    private void jBuscadorDePregKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscadorDePregKeyReleased
        // Filtrado de objetos en la lista que contienen la letra en cuestion
        boolean option = true;
        String texto = jBuscadorDePreg.getText();
        
        
        jTablePreguntas.setModel(controladora.vistaManagement.setModeloTablaPreguntas(option,texto));
        JTableHeader tableHeader = jTablePreguntas.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);


        jTablePreguntas.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePreguntas.getColumnModel().getColumn(1).setPreferredWidth(800);
        jTablePreguntas.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTablePreguntas.setAutoResizeMode(jTablePreguntas.AUTO_RESIZE_LAST_COLUMN);
        jTablePreguntas.setRowHeight(20);
        jScrollPanePreguntas.setVisible(true);
        jTablePreguntas.setVisible(true);


        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTablePreguntas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
    }//GEN-LAST:event_jBuscadorDePregKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfazAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Banner;
    private javax.swing.JTextField Opcion1;
    private javax.swing.JTextField Opcion2;
    private javax.swing.JTextField Opcion3;
    private javax.swing.JTextField Opcion4;
    private javax.swing.JTextField Pregunta;
    private javax.swing.JLabel Presupuesto;
    private javax.swing.ButtonGroup buttonGroupOpcionCorrecta;
    private javax.swing.JButton cargarImagen;
    private javax.swing.JLabel catalogo;
    private javax.swing.JCheckBox editingCheck;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jBotonDeBuscar;
    private javax.swing.JTextField jBuscadorDePreg;
    private javax.swing.JButton jButtonAgregarPregunta;
    private javax.swing.JButton jButtonAgregarPregunta1;
    private javax.swing.JButton jCalcularPresupuesto;
    private javax.swing.JLabel jInstruccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPaneFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanelButtonGuide;
    private javax.swing.JPanel jPanelGuide;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPanePreguntas;
    private javax.swing.JComboBox<String> jSeleccionarMaterial1;
    private javax.swing.JComboBox<String> jSeleccionarMaterial2;
    private javax.swing.JComboBox<String> jSeleccionarMaterial3;
    private javax.swing.JPanel jTabEditarPregunta;
    private javax.swing.JPanel jTabMateriales;
    private javax.swing.JPanel jTabPreguntas;
    private javax.swing.JPanel jTabPresupuesto;
    private javax.swing.JTable jTablePreguntas;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel materiales;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JTabbedPane pestanas;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
