/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import javax.swing.table.JTableHeader;
import java.awt.Font;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.JOptionPane;
import modelo.Pregunta;
import modelo.Material;
import java.util.InputMismatchException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import controladora.ListaManagement;

/**
 *
 * @author umaru
 */
public class InterfazAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DetalleObra
     */
    public InterfazAdmin() {
        initComponents();
        Font fuentenegrita = new Font("Arial",Font.BOLD,36);
        preguntas.setFont(fuentenegrita);
        pestanas.setSelectedIndex(0);
        jTablePreguntas.setModel(controladora.vistaManagement.setModeloTablaPreguntas(false, ""));
        JTableHeader tableHeader = jTablePreguntas.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);


        jTablePreguntas.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePreguntas.getColumnModel().getColumn(1).setPreferredWidth(800);
        jTablePreguntas.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTablePreguntas.setAutoResizeMode(jTablePreguntas.AUTO_RESIZE_LAST_COLUMN);
        jTablePreguntas.setRowHeight(20);
        jScrollPanePreguntas.setVisible(true);
        jTablePreguntas.setVisible(true);


        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTablePreguntas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOpcionCorrecta = new javax.swing.ButtonGroup();
        jPaneFondo = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jButtonAgregarPregunta1 = new javax.swing.JButton();
        pestanas = new javax.swing.JTabbedPane();
        jTabPreguntas = new javax.swing.JPanel();
        jScrollPanePreguntas = new javax.swing.JScrollPane();
        jTablePreguntas = new javax.swing.JTable();
        jButtonAgregarPregunta = new javax.swing.JButton();
        jBuscadorDePreg = new javax.swing.JTextField();
        jBotonDeBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabMateriales = new javax.swing.JPanel();
        jScrollPaneMateriales = new javax.swing.JScrollPane();
        jTableMateriales = new javax.swing.JTable();
        jButtonAgregarMaterial = new javax.swing.JButton();
        jBuscadorDeMat = new javax.swing.JTextField();
        jBotonDeBuscarMat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabPresupuesto = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jInstruccion = new javax.swing.JLabel();
        jSeleccionarMaterialSuelo = new javax.swing.JComboBox<>();
        jSeleccionarMaterialTecho = new javax.swing.JComboBox<>();
        jSeleccionarMaterialParedes = new javax.swing.JComboBox<>();
        jCostosAdicionales = new javax.swing.JTextField();
        jCalcularPresupuesto = new javax.swing.JButton();
        jResultadoPan = new javax.swing.JPanel();
        jResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTabEditarPregunta = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jPanelGuide = new javax.swing.JPanel();
        Pregunta = new javax.swing.JTextField();
        Opcion1 = new javax.swing.JTextField();
        Opcion4 = new javax.swing.JTextField();
        Opcion3 = new javax.swing.JTextField();
        Opcion2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        lError = new javax.swing.JLabel();
        jPanelButtonGuide = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        cargarImagen = new javax.swing.JButton();
        guardarCambios = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jTabEditarMaterial = new javax.swing.JPanel();
        Background1 = new javax.swing.JPanel();
        jPanelGuide1 = new javax.swing.JPanel();
        jNombre = new javax.swing.JTextField();
        jCostoVolumen = new javax.swing.JTextField();
        jCostoArea = new javax.swing.JTextField();
        lErrorMat = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelButtonGuide1 = new javax.swing.JPanel();
        volverMat = new javax.swing.JButton();
        guardarCambiosMat = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        editingCheck = new javax.swing.JCheckBox();
        menu1 = new javax.swing.JPanel();
        preguntas = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        materiales = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        presupuesto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPaneFondo.setBackground(new java.awt.Color(153, 153, 153));
        jPaneFondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPaneFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setBackground(new java.awt.Color(78, 95, 23));
        Banner.setPreferredSize(new java.awt.Dimension(1280, 160));
        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(213, 223, 181));
        jLabel4.setText("CABINAS AZULES");
        Banner.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 436, 36));

        jLabel6.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(213, 223, 181));
        jLabel6.setText("Inicio de sesion");
        Banner.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 436, 36));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/glasses.png"))); // NOI18N
        Banner.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButtonAgregarPregunta1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonAgregarPregunta1.setForeground(new java.awt.Color(123, 58, 0));
        jButtonAgregarPregunta1.setText("Volver al inicio");
        jButtonAgregarPregunta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarPregunta1MouseClicked(evt);
            }
        });
        jButtonAgregarPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPregunta1ActionPerformed(evt);
            }
        });
        Banner.add(jButtonAgregarPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, 170, 48));

        jPaneFondo.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pestanas.setBackground(new java.awt.Color(204, 204, 204));
        pestanas.setForeground(new java.awt.Color(204, 204, 204));

        jTabPreguntas.setBackground(new java.awt.Color(255, 242, 223));
        jTabPreguntas.setMaximumSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setMinimumSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setPreferredSize(new java.awt.Dimension(1010, 582));
        jTabPreguntas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePreguntas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTablePreguntas.setForeground(new java.awt.Color(123, 58, 0));
        jTablePreguntas.setRowHeight(50);
        jTablePreguntas.setRowSelectionAllowed(false);
        jTablePreguntas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablePreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTablePreguntasMousePressed(evt);
            }
        });
        jScrollPanePreguntas.setViewportView(jTablePreguntas);

        jTabPreguntas.add(jScrollPanePreguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 137, 960, 415));

        jButtonAgregarPregunta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonAgregarPregunta.setForeground(new java.awt.Color(123, 58, 0));
        jButtonAgregarPregunta.setText("Agregar pregunta");
        jButtonAgregarPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarPreguntaMouseClicked(evt);
            }
        });
        jButtonAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPreguntaActionPerformed(evt);
            }
        });
        jTabPreguntas.add(jButtonAgregarPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 47, 170, 48));

        jBuscadorDePreg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBuscadorDePreg.setForeground(new java.awt.Color(163, 98, 40));
        jBuscadorDePreg.setText("Buscar...");
        jBuscadorDePreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuscadorDePregMouseClicked(evt);
            }
        });
        jBuscadorDePreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscadorDePregActionPerformed(evt);
            }
        });
        jBuscadorDePreg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBuscadorDePregKeyReleased(evt);
            }
        });
        jTabPreguntas.add(jBuscadorDePreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 47, 589, 50));

        jBotonDeBuscar.setBackground(new java.awt.Color(78, 95, 23));
        jBotonDeBuscar.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/magnifier.png"))); // NOI18N
        jLabel1.setIconTextGap(0);

        javax.swing.GroupLayout jBotonDeBuscarLayout = new javax.swing.GroupLayout(jBotonDeBuscar);
        jBotonDeBuscar.setLayout(jBotonDeBuscarLayout);
        jBotonDeBuscarLayout.setHorizontalGroup(
            jBotonDeBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBotonDeBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jBotonDeBuscarLayout.setVerticalGroup(
            jBotonDeBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBotonDeBuscarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabPreguntas.add(jBotonDeBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 47, -1, -1));

        pestanas.addTab("tab1", jTabPreguntas);

        jTabMateriales.setBackground(new java.awt.Color(255, 242, 223));
        jTabMateriales.setMaximumSize(new java.awt.Dimension(1010, 582));
        jTabMateriales.setMinimumSize(new java.awt.Dimension(1010, 582));
        jTabMateriales.setPreferredSize(new java.awt.Dimension(1010, 582));
        jTabMateriales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPaneMaterialesMousePressed(evt);
            }
        });

        jTableMateriales.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTableMateriales.setForeground(new java.awt.Color(123, 58, 0));
        jTableMateriales.setRowHeight(50);
        jTableMateriales.setRowSelectionAllowed(false);
        jTableMateriales.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableMaterialesMousePressed(evt);
            }
        });
        jScrollPaneMateriales.setViewportView(jTableMateriales);
        if (jTableMateriales.getColumnModel().getColumnCount() > 0) {
            jTableMateriales.getColumnModel().getColumn(0).setHeaderValue("Nº");
            jTableMateriales.getColumnModel().getColumn(1).setHeaderValue("Pregunta");
            jTableMateriales.getColumnModel().getColumn(2).setHeaderValue("% de acierto");
        }

        jTabMateriales.add(jScrollPaneMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 137, 960, 415));

        jButtonAgregarMaterial.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonAgregarMaterial.setForeground(new java.awt.Color(123, 58, 0));
        jButtonAgregarMaterial.setText("Agregar material");
        jButtonAgregarMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarMaterialMouseClicked(evt);
            }
        });
        jButtonAgregarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMaterialActionPerformed(evt);
            }
        });
        jTabMateriales.add(jButtonAgregarMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 47, 170, 48));

        jBuscadorDeMat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBuscadorDeMat.setForeground(new java.awt.Color(163, 98, 40));
        jBuscadorDeMat.setText("Buscar...");
        jBuscadorDeMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuscadorDeMatMouseClicked(evt);
            }
        });
        jBuscadorDeMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscadorDeMatActionPerformed(evt);
            }
        });
        jBuscadorDeMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBuscadorDeMatKeyReleased(evt);
            }
        });
        jTabMateriales.add(jBuscadorDeMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 47, 589, 50));

        jBotonDeBuscarMat.setBackground(new java.awt.Color(78, 95, 23));
        jBotonDeBuscarMat.setPreferredSize(new java.awt.Dimension(50, 50));
        jBotonDeBuscarMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotonDeBuscarMatMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/magnifier.png"))); // NOI18N
        jLabel2.setIconTextGap(0);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jBotonDeBuscarMatLayout = new javax.swing.GroupLayout(jBotonDeBuscarMat);
        jBotonDeBuscarMat.setLayout(jBotonDeBuscarMatLayout);
        jBotonDeBuscarMatLayout.setHorizontalGroup(
            jBotonDeBuscarMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBotonDeBuscarMatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jBotonDeBuscarMatLayout.setVerticalGroup(
            jBotonDeBuscarMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBotonDeBuscarMatLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabMateriales.add(jBotonDeBuscarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 47, -1, -1));

        pestanas.addTab("tab1", jTabMateriales);

        jPanel18.setBackground(new java.awt.Color(255, 242, 223));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInstruccion.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jInstruccion.setForeground(new java.awt.Color(123, 58, 0));
        jInstruccion.setText("Seleccione los materiales a utilizar");
        jPanel18.add(jInstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jSeleccionarMaterialSuelo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jSeleccionarMaterialSuelo.setForeground(new java.awt.Color(123, 58, 0));
        jSeleccionarMaterialSuelo.setToolTipText("");
        jPanel18.add(jSeleccionarMaterialSuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 580, 50));

        jSeleccionarMaterialTecho.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jSeleccionarMaterialTecho.setForeground(new java.awt.Color(123, 58, 0));
        jSeleccionarMaterialTecho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jSeleccionarMaterialTecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeleccionarMaterialTechoActionPerformed(evt);
            }
        });
        jPanel18.add(jSeleccionarMaterialTecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 580, 50));

        jSeleccionarMaterialParedes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jSeleccionarMaterialParedes.setForeground(new java.awt.Color(123, 58, 0));
        jSeleccionarMaterialParedes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel18.add(jSeleccionarMaterialParedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 580, 50));

        jCostosAdicionales.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCostosAdicionales.setForeground(new java.awt.Color(123, 58, 0));
        jCostosAdicionales.setText("0");
        jCostosAdicionales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCostosAdicionalesMouseClicked(evt);
            }
        });
        jCostosAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCostosAdicionalesActionPerformed(evt);
            }
        });
        jPanel18.add(jCostosAdicionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 580, 50));

        jCalcularPresupuesto.setBackground(new java.awt.Color(78, 95, 23));
        jCalcularPresupuesto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCalcularPresupuesto.setForeground(new java.awt.Color(213, 223, 181));
        jCalcularPresupuesto.setText("Calcular presupuesto");
        jCalcularPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalcularPresupuestoActionPerformed(evt);
            }
        });
        jPanel18.add(jCalcularPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 250, 50));

        jResultadoPan.setBackground(new java.awt.Color(123, 58, 0));

        jResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jResultado.setForeground(new java.awt.Color(255, 242, 223));
        jResultado.setText(".   .   .");

        javax.swing.GroupLayout jResultadoPanLayout = new javax.swing.GroupLayout(jResultadoPan);
        jResultadoPan.setLayout(jResultadoPanLayout);
        jResultadoPanLayout.setHorizontalGroup(
            jResultadoPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultadoPanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jResultadoPanLayout.setVerticalGroup(
            jResultadoPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResultadoPanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel18.add(jResultadoPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 250, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(123, 58, 0));
        jLabel3.setText("Paredes");
        jPanel18.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jError.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jError.setForeground(new java.awt.Color(255, 0, 0));
        jPanel18.add(jError, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 600, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(123, 58, 0));
        jLabel7.setText("Techo");
        jPanel18.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(123, 58, 0));
        jLabel8.setText("Suelo");
        jPanel18.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(123, 58, 0));
        jLabel9.setText("Costos adicionales");
        jPanel18.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        javax.swing.GroupLayout jTabPresupuestoLayout = new javax.swing.GroupLayout(jTabPresupuesto);
        jTabPresupuesto.setLayout(jTabPresupuestoLayout);
        jTabPresupuestoLayout.setHorizontalGroup(
            jTabPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTabPresupuestoLayout.setVerticalGroup(
            jTabPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pestanas.addTab("tab3", jTabPresupuesto);

        jTabEditarPregunta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabEditarPreguntaMouseClicked(evt);
            }
        });

        Background.setBackground(new java.awt.Color(255, 242, 223));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setFocusable(false);
        imagen.setMaximumSize(new java.awt.Dimension(200, 290));
        imagen.setMinimumSize(new java.awt.Dimension(200, 290));
        imagen.setOpaque(true);
        imagen.setPreferredSize(new java.awt.Dimension(200, 290));
        Background.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 290));

        jPanelGuide.setBackground(new java.awt.Color(255, 242, 223));

        Pregunta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Pregunta.setForeground(new java.awt.Color(123, 58, 0));
        Pregunta.setToolTipText("Ingresar enunciado de pregunta");
        Pregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreguntaActionPerformed(evt);
            }
        });

        Opcion1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Opcion1.setForeground(new java.awt.Color(123, 58, 0));
        Opcion1.setToolTipText("Ingresar opcion 1");
        Opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion1ActionPerformed(evt);
            }
        });

        Opcion4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Opcion4.setForeground(new java.awt.Color(123, 58, 0));
        Opcion4.setToolTipText("Ingresar opcion 4");
        Opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion4ActionPerformed(evt);
            }
        });

        Opcion3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Opcion3.setForeground(new java.awt.Color(123, 58, 0));
        Opcion3.setToolTipText("Ingresar opcion 3");
        Opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion3ActionPerformed(evt);
            }
        });

        Opcion2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Opcion2.setForeground(new java.awt.Color(123, 58, 0));
        Opcion2.setToolTipText("Ingresar opcion 2");
        Opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcion2ActionPerformed(evt);
            }
        });

        buttonGroupOpcionCorrecta.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(123, 58, 0));
        jRadioButton1.setText("Opcion 1:");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroupOpcionCorrecta.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(123, 58, 0));
        jRadioButton2.setText("Opcion 2:");

        buttonGroupOpcionCorrecta.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(123, 58, 0));
        jRadioButton3.setText("Opcion 3:");

        buttonGroupOpcionCorrecta.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(123, 58, 0));
        jRadioButton4.setText("Opcion 4:");

        lError.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lError.setForeground(new java.awt.Color(255, 0, 0));
        lError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelGuideLayout = new javax.swing.GroupLayout(jPanelGuide);
        jPanelGuide.setLayout(jPanelGuideLayout);
        jPanelGuideLayout.setHorizontalGroup(
            jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuideLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(lError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelGuideLayout.createSequentialGroup()
                        .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Opcion3)
                            .addComponent(Opcion2)
                            .addComponent(Opcion1)
                            .addComponent(Opcion4))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanelGuideLayout.setVerticalGroup(
            jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuideLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanelGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        Background.add(jPanelGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 740, 390));

        jPanelButtonGuide.setBackground(new java.awt.Color(255, 242, 223));

        volver.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(123, 58, 0));
        volver.setText("Atrás");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        cargarImagen.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cargarImagen.setForeground(new java.awt.Color(123, 58, 0));
        cargarImagen.setText("Cargar Imagen");
        cargarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarImagenMouseClicked(evt);
            }
        });
        cargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarImagenActionPerformed(evt);
            }
        });

        guardarCambios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        guardarCambios.setForeground(new java.awt.Color(123, 58, 0));
        guardarCambios.setText("Guardar");
        guardarCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarCambiosMouseClicked(evt);
            }
        });
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(123, 58, 0));
        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonGuideLayout = new javax.swing.GroupLayout(jPanelButtonGuide);
        jPanelButtonGuide.setLayout(jPanelButtonGuideLayout);
        jPanelButtonGuideLayout.setHorizontalGroup(
            jPanelButtonGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonGuideLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonGuideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelButtonGuideLayout.setVerticalGroup(
            jPanelButtonGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonGuideLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelButtonGuideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Background.add(jPanelButtonGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 1000, 180));

        javax.swing.GroupLayout jTabEditarPreguntaLayout = new javax.swing.GroupLayout(jTabEditarPregunta);
        jTabEditarPregunta.setLayout(jTabEditarPreguntaLayout);
        jTabEditarPreguntaLayout.setHorizontalGroup(
            jTabEditarPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTabEditarPreguntaLayout.setVerticalGroup(
            jTabEditarPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pestanas.addTab("tab4", jTabEditarPregunta);

        jTabEditarMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabEditarMaterialMouseClicked(evt);
            }
        });

        Background1.setBackground(new java.awt.Color(255, 242, 223));
        Background1.setMinimumSize(new java.awt.Dimension(1000, 580));
        Background1.setPreferredSize(new java.awt.Dimension(1000, 580));
        Background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGuide1.setBackground(new java.awt.Color(255, 242, 223));
        jPanelGuide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNombre.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jNombre.setForeground(new java.awt.Color(123, 58, 0));
        jNombre.setToolTipText("Ingresar nombre del material");
        jNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jNombreMouseEntered(evt);
            }
        });
        jNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreActionPerformed(evt);
            }
        });
        jPanelGuide1.add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 485, 55));

        jCostoVolumen.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jCostoVolumen.setForeground(new java.awt.Color(123, 58, 0));
        jCostoVolumen.setToolTipText("Ingresar costo por volumen");
        jCostoVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCostoVolumenActionPerformed(evt);
            }
        });
        jPanelGuide1.add(jCostoVolumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 486, 56));

        jCostoArea.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jCostoArea.setForeground(new java.awt.Color(123, 58, 0));
        jCostoArea.setToolTipText("Ingresar costo por área");
        jCostoArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCostoAreaActionPerformed(evt);
            }
        });
        jPanelGuide1.add(jCostoArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 486, 55));

        lErrorMat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lErrorMat.setForeground(new java.awt.Color(255, 0, 0));
        lErrorMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelGuide1.add(lErrorMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 7, 620, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(123, 58, 0));
        jLabel10.setText("Costo por volumen");
        jPanelGuide1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 269, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(123, 58, 0));
        jLabel11.setText("Costo por área");
        jPanelGuide1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(123, 58, 0));
        jLabel12.setText("Nombre");
        jPanelGuide1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        Background1.add(jPanelGuide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 810, 280));

        jPanelButtonGuide1.setBackground(new java.awt.Color(255, 242, 223));

        volverMat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        volverMat.setForeground(new java.awt.Color(123, 58, 0));
        volverMat.setText("Atrás");
        volverMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMatMouseClicked(evt);
            }
        });
        volverMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverMatActionPerformed(evt);
            }
        });

        guardarCambiosMat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        guardarCambiosMat.setForeground(new java.awt.Color(123, 58, 0));
        guardarCambiosMat.setText("Guardar");
        guardarCambiosMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarCambiosMatMouseClicked(evt);
            }
        });
        guardarCambiosMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosMatActionPerformed(evt);
            }
        });

        Borrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Borrar.setForeground(new java.awt.Color(123, 58, 0));
        Borrar.setText("Eliminar");
        Borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrarMouseClicked(evt);
            }
        });
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonGuide1Layout = new javax.swing.GroupLayout(jPanelButtonGuide1);
        jPanelButtonGuide1.setLayout(jPanelButtonGuide1Layout);
        jPanelButtonGuide1Layout.setHorizontalGroup(
            jPanelButtonGuide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonGuide1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(guardarCambiosMat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addComponent(volverMat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanelButtonGuide1Layout.setVerticalGroup(
            jPanelButtonGuide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonGuide1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanelButtonGuide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverMat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarCambiosMat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        Background1.add(jPanelButtonGuide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 950, 130));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(123, 58, 0));
        jLabel5.setText("Edición de material");
        Background1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        javax.swing.GroupLayout jTabEditarMaterialLayout = new javax.swing.GroupLayout(jTabEditarMaterial);
        jTabEditarMaterial.setLayout(jTabEditarMaterialLayout);
        jTabEditarMaterialLayout.setHorizontalGroup(
            jTabEditarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jTabEditarMaterialLayout.setVerticalGroup(
            jTabEditarMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pestanas.addTab("tab4", jTabEditarMaterial);

        editingCheck.setText("Editando");
        editingCheck.setToolTipText("");
        editingCheck.setFocusable(false);
        pestanas.addTab("tab5", editingCheck);

        jPaneFondo.add(pestanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 1010, 620));
        pestanas.getAccessibleContext().setAccessibleName("");
        pestanas.getAccessibleContext().setAccessibleDescription("");

        menu1.setBackground(new java.awt.Color(213, 223, 181));
        menu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu1MouseMoved(evt);
            }
        });
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        preguntas.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        preguntas.setForeground(new java.awt.Color(78, 95, 23));
        preguntas.setText("Preguntas");

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(preguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(preguntas)
                .addGap(56, 56, 56))
        );

        jPaneFondo.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 180));

        menu2.setBackground(new java.awt.Color(213, 223, 181));
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        materiales.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        materiales.setForeground(new java.awt.Color(78, 95, 23));
        materiales.setText("Materiales");

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(materiales)
                .addGap(51, 51, 51))
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(materiales)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPaneFondo.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 200));

        menu3.setBackground(new java.awt.Color(213, 223, 181));
        menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu3MouseClicked(evt);
            }
        });

        presupuesto.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        presupuesto.setForeground(new java.awt.Color(78, 95, 23));
        presupuesto.setText("Presupuesto");

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(presupuesto)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        menu3Layout.setVerticalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(presupuesto)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPaneFondo.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 535, 270, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPaneFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 739, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        int actual = pestanas.getSelectedIndex();
        Font fuentenegrita = new Font("Arial",Font.BOLD,36);
        Font fuenteplain = new Font("Arial",Font.PLAIN,36);
        switch (actual){ 
            case 0,3:
                preguntas.setFont(fuenteplain);
                break;
            case 1,4: 
                materiales.setFont(fuenteplain);
                break;
            case 2:
                presupuesto.setFont(fuenteplain);
                break;
        }
        preguntas.setFont(fuentenegrita);
        
        pestanas.setSelectedIndex(0);
        jTablePreguntas.setModel(controladora.vistaManagement.setModeloTablaPreguntas(false,""));
        JTableHeader tableHeader = jTablePreguntas.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);
        
        
        jTablePreguntas.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePreguntas.getColumnModel().getColumn(1).setPreferredWidth(800);
        jTablePreguntas.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTablePreguntas.setAutoResizeMode(jTablePreguntas.AUTO_RESIZE_LAST_COLUMN);
        jTablePreguntas.setRowHeight(20);
        jScrollPanePreguntas.setVisible(true);
        jTablePreguntas.setVisible(true);
        
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTablePreguntas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        
    }//GEN-LAST:event_menu1MouseClicked

    private void menu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseMoved
        
    }//GEN-LAST:event_menu1MouseMoved

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        int actual = pestanas.getSelectedIndex();
        Font fuentenegrita = new Font("Arial",Font.BOLD,36);
        Font fuenteplain = new Font("Arial",Font.PLAIN,36);
        switch (actual){ 
            case 0,3:
                preguntas.setFont(fuenteplain);
                break;
            case 1,4: 
                materiales.setFont(fuenteplain);
                break;
            case 2:
                presupuesto.setFont(fuenteplain);
                break;
        }
        materiales.setFont(fuentenegrita);
        
        pestanas.setSelectedIndex(1);
        jTableMateriales.setModel(controladora.vistaManagement.setModeloTablaMateriales(false,""));
        JTableHeader tableHeader = jTableMateriales.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);
        
        
        jTableMateriales.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableMateriales.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableMateriales.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableMateriales.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableMateriales.setAutoResizeMode(jTableMateriales.AUTO_RESIZE_LAST_COLUMN);
        jTableMateriales.setRowHeight(20);
        jScrollPaneMateriales.setVisible(true);
        jTableMateriales.setVisible(true);
        
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTableMateriales.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
    }//GEN-LAST:event_menu2MouseClicked

    private void menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3MouseClicked
        int actual = pestanas.getSelectedIndex();
        Font fuentenegrita = new Font("Arial",Font.BOLD,36);
        Font fuenteplain = new Font("Arial",Font.PLAIN,36);
        switch (actual){ 
            case 0,3:
                preguntas.setFont(fuenteplain);
                break;
            case 1,4: 
                materiales.setFont(fuenteplain);
                break;
            case 2:
                presupuesto.setFont(fuenteplain);
                break;
        }
        presupuesto.setFont(fuentenegrita);
        jError.setText("");
        jCostosAdicionales.setText("0");
        jResultado.setText(".  .  .");
        
        jSeleccionarMaterialSuelo.setModel(controladora.vistaManagement.setModeloCBMateriales());
        jSeleccionarMaterialTecho.setModel(controladora.vistaManagement.setModeloCBMateriales());
        jSeleccionarMaterialParedes.setModel(controladora.vistaManagement.setModeloCBMateriales());

        pestanas.setSelectedIndex(2);
    }//GEN-LAST:event_menu3MouseClicked

    private void jButtonAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntaActionPerformed
        // POPUP agregar pregunta y definir opciones
    }//GEN-LAST:event_jButtonAgregarPreguntaActionPerformed

    private void jBuscadorDePregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscadorDePregActionPerformed
        jBuscadorDePreg.setText("");
    }//GEN-LAST:event_jBuscadorDePregActionPerformed

    private void jBuscadorDePregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscadorDePregMouseClicked
        jBuscadorDePreg.setText("");
    }//GEN-LAST:event_jBuscadorDePregMouseClicked

    private void jButtonAgregarPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPregunta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarPregunta1ActionPerformed

    private void jButtonAgregarPregunta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarPregunta1MouseClicked
        this.dispose();
        controladora.vistaManagement.loadStart();
    }//GEN-LAST:event_jButtonAgregarPregunta1MouseClicked

    private void jSeleccionarMaterialTechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeleccionarMaterialTechoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeleccionarMaterialTechoActionPerformed

    private void jCostosAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCostosAdicionalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCostosAdicionalesActionPerformed

    private void jButtonAgregarPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarPreguntaMouseClicked
        Opcion1.setText("");
        Opcion2.setText("");
        Opcion3.setText("");
        Opcion4.setText("");
        Pregunta.setText("");
        lError.setText("");
        buttonGroupOpcionCorrecta.clearSelection();
        imagen.setIcon(null);
        pestanas.setSelectedIndex(3);
        Eliminar.setVisible(false);
        editingCheck.setSelected(false);
    }//GEN-LAST:event_jButtonAgregarPreguntaMouseClicked

    private void Opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion1ActionPerformed

    private void PreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreguntaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        
    }//GEN-LAST:event_volverActionPerformed

    private void cargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarImagenActionPerformed

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        /*ListaManagement vMan = new ListaManagement();
        int vRespuesta;
        if(jRadioButton1.isSelected()){
            vRespuesta=1;
        }else{
            if(jRadioButton2.isSelected()){
                vRespuesta=2;
            }else{
                if(jRadioButton3.isSelected()){
                    vRespuesta=3;
                }else{
                    vRespuesta=4;
                }
            }
        }
        if(Pregunta.getText().isBlank() || Opcion1.getText().isBlank() || Opcion2.getText().isBlank() || Opcion3.getText().isBlank() || Opcion4.getText().isBlank()){
            lError.setText("Se deben rellenar todos los campos antes de guardar.");
        }else{
            vMan.guardarPregunta(Pregunta.getText(), new String[]{Opcion1.getText(),Opcion2.getText(),Opcion3.getText(),Opcion4.getText()}, vRespuesta, "");
        }*/
    }//GEN-LAST:event_guardarCambiosActionPerformed

    private void Opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion2ActionPerformed

    private void Opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion3ActionPerformed

    private void Opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcion4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void guardarCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarCambiosMouseClicked
        // GUARDAR CAMBIOS
        String opc1, opc2, opc3, opc4, enunciado = "";
        ListaManagement vMan = new ListaManagement();
        int respuestaCorrecta = 0;
       
        if(Pregunta.getText().isBlank() || Opcion1.getText().isBlank() || Opcion2.getText().isBlank() || Opcion3.getText().isBlank() || Opcion4.getText().isBlank()){
            lError.setText("Se deben rellenar todos los campos antes de guardar.");
            return;
        }
        opc1 = (Opcion1.getText()!=null) ? Opcion1.getText() : " " ;
        opc2 = (Opcion2.getText()!=null) ? Opcion2.getText() : " " ;
        opc3 = (Opcion3.getText()!=null) ? Opcion3.getText() : " " ;
        opc4 = (Opcion4.getText()!=null) ? Opcion4.getText() : " " ;
        
        
        String[] opciones = new String[]{opc1,opc2,opc3,opc4};
        enunciado = Pregunta.getText();
        
        if(jRadioButton1.isSelected()){respuestaCorrecta = 1;} 
        if(jRadioButton2.isSelected()){respuestaCorrecta = 2;}
        if(jRadioButton3.isSelected()){respuestaCorrecta = 3;}
        if(jRadioButton4.isSelected()){respuestaCorrecta = 4;}
        
        //Entra aqui si el usuario no ha ingresado ninguna opcion como la correcta
        if(respuestaCorrecta == 0){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna opcion como la correcta.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{ 
            // Entra aqui si la pregunta paso los requerimientos para ser agregada al sistema.
            if(!editingCheck.isSelected()){
                // AGREGANDO PREGUNTA
                Pregunta P1  = new Pregunta(enunciado,opciones,respuestaCorrecta,modelo.globalAccess.imagePath.get(0));
                vMan.AddPregunta(P1);
            }else{
                // EDITANDO PREGUNTA
                int location=jTablePreguntas.getSelectedRow();
                modelo.globalAccess.listaDePreguntas.get(location).setEnunciado(enunciado);
                modelo.globalAccess.listaDePreguntas.get(location).setOpciones(opciones);
                modelo.globalAccess.listaDePreguntas.get(location).setRespuestacorrecta(respuestaCorrecta);
                if(!modelo.globalAccess.imagePath.get(0).isEmpty()){
                    modelo.globalAccess.listaDePreguntas.get(location).setImagePath(modelo.globalAccess.imagePath.get(0));
                }                
            }
            vMan.guardarPregunta();
            //RESETEAR LOS TEXTOS Y OPCIONES
            opciones = null;
            Opcion1.setText("");
            Opcion2.setText("");
            Opcion3.setText("");
            Opcion4.setText("");
            Pregunta.setText("");
            buttonGroupOpcionCorrecta.clearSelection();
            imagen.setIcon(null);
            modelo.globalAccess.imagePath.set(0,"");
            
            // LIMPIAR EL ARRAY CON LA IMAGEN modelo.globalAccess.imagePath.add(file_path);
            
            pestanas.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Pregunta guardada exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            
            //REFRESCAR LA TABLA
            jTablePreguntas.setModel(controladora.vistaManagement.setModeloTablaPreguntas(false, ""));
            JTableHeader tableHeader = jTablePreguntas.getTableHeader();
            Font headerFont = new Font("Arial", Font.BOLD, 18);
            float[] hsbColor = new float[3];
            Color.RGBtoHSB(163, 58, 0, hsbColor);
            tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
            tableHeader.setFont(headerFont);


            jTablePreguntas.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTablePreguntas.getColumnModel().getColumn(1).setPreferredWidth(800);
            jTablePreguntas.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTablePreguntas.setAutoResizeMode(jTablePreguntas.AUTO_RESIZE_LAST_COLUMN);
            jTablePreguntas.setRowHeight(20);
            jScrollPanePreguntas.setVisible(true);
            jTablePreguntas.setVisible(true);


            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment( JLabel.CENTER );
            jTablePreguntas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        }
    }//GEN-LAST:event_guardarCambiosMouseClicked

    private void jTabEditarPreguntaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabEditarPreguntaMouseClicked

    }//GEN-LAST:event_jTabEditarPreguntaMouseClicked

    private void cargarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarImagenMouseClicked
        JFileChooser elegirImagen = new JFileChooser();
        
        int res = elegirImagen.showSaveDialog(null);
        
        if(res == JFileChooser.APPROVE_OPTION){
            String file_path = elegirImagen.getSelectedFile().getAbsolutePath();
            
            modelo.globalAccess.imagePath.set(0,file_path);
            
            ImageIcon icon = new ImageIcon(file_path);
            
            //hacer que la imagen haga resize para el recuadro
            Image imageToResize = icon.getImage();
            Image resizedImage = imageToResize.getScaledInstance(imagen.getWidth(),imagen.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon resizedIcon = new ImageIcon(resizedImage);
            
            // Set el icono dentro del label
            imagen.setIcon(resizedIcon);
        }
            
    }//GEN-LAST:event_cargarImagenMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        Opcion1.setText("");
        Opcion2.setText("");
        Opcion3.setText("");
        Opcion4.setText("");
        Pregunta.setText("");
        buttonGroupOpcionCorrecta.clearSelection();
        imagen.setIcon(null);
        editingCheck.setSelected(false); 
        pestanas.setSelectedIndex(0);
    }//GEN-LAST:event_volverMouseClicked

    private void jTablePreguntasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePreguntasMousePressed

        pestanas.setSelectedIndex(3); 
        
        Eliminar.setVisible(true);
        //Numero de columna a la que le dieron click/INDICE DEL OBJETO EN EL ARRAYLIST
        int location=jTablePreguntas.getSelectedRow();
        
        // Mostrar las opciones actuales de la pregunta anterior
        Opcion1.setText(modelo.globalAccess.listaDePreguntas.get(location).getOpciones()[0]);
        Opcion2.setText(modelo.globalAccess.listaDePreguntas.get(location).getOpciones()[1]);
        Opcion3.setText(modelo.globalAccess.listaDePreguntas.get(location).getOpciones()[2]);
        Opcion4.setText(modelo.globalAccess.listaDePreguntas.get(location).getOpciones()[3]);
        Pregunta.setText(modelo.globalAccess.listaDePreguntas.get(location).getEnunciado());
        
        ImageIcon icon = new ImageIcon(modelo.globalAccess.listaDePreguntas.get(location).getImagePath());
        //hacer que la imagen haga resize para el recuadro
        Image imageToResize = icon.getImage();
        Image resizedImage = imageToResize.getScaledInstance(imagen.getWidth(),imagen.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizedImage);

        // Set el icono dentro del label
        imagen.setIcon(resizedIcon);
        
        // Set el boton que indica cual es la correcta
        switch(modelo.globalAccess.listaDePreguntas.get(location).getRespuestacorrecta()){
            case 1:
                jRadioButton1.setSelected(true);
                break;
            case 2:
                jRadioButton2.setSelected(true);
                break;
            case 3:
                jRadioButton3.setSelected(true);
                break;
            case 4:
                jRadioButton4.setSelected(true);
                break;
        }
    
        
        //para indicarle que estamos editando una pregunta que ya existe
        editingCheck.setSelected(true); 
    }//GEN-LAST:event_jTablePreguntasMousePressed

    private void jBuscadorDePregKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscadorDePregKeyReleased
        // Filtrado de objetos en la lista que contienen la letra en cuestion
        boolean option = true;
        String texto = jBuscadorDePreg.getText();
        
        
        jTablePreguntas.setModel(controladora.vistaManagement.setModeloTablaPreguntas(option,texto));
        JTableHeader tableHeader = jTablePreguntas.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);


        jTablePreguntas.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePreguntas.getColumnModel().getColumn(1).setPreferredWidth(800);
        jTablePreguntas.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTablePreguntas.setAutoResizeMode(jTablePreguntas.AUTO_RESIZE_LAST_COLUMN);
        jTablePreguntas.setRowHeight(20);
        jScrollPanePreguntas.setVisible(true);
        jTablePreguntas.setVisible(true);


        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTablePreguntas.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
    }//GEN-LAST:event_jBuscadorDePregKeyReleased

    private void jCostosAdicionalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCostosAdicionalesMouseClicked
        jCostosAdicionales.setText("");
    }//GEN-LAST:event_jCostosAdicionalesMouseClicked

    private void jCalcularPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalcularPresupuestoActionPerformed
        try{
            jError.setText("");
            controladora.Presupuesto presup = new controladora.Presupuesto();
            if(jSeleccionarMaterialSuelo.getSelectedIndex()>modelo.globalAccess.listaDeMateriales.size() || jSeleccionarMaterialTecho.getSelectedIndex()>modelo.globalAccess.listaDeMateriales.size() || jSeleccionarMaterialSuelo.getSelectedIndex()>modelo.globalAccess.listaDeMateriales.size() || jSeleccionarMaterialSuelo.getSelectedIndex()<0 || jSeleccionarMaterialTecho.getSelectedIndex()<0 || jSeleccionarMaterialSuelo.getSelectedIndex()<0){
                throw new ArrayIndexOutOfBoundsException("¡Error! Debe seleccionar opciones validas.");
            }
            String resultado = String.valueOf(presup.calcularPresupuesto(jSeleccionarMaterialSuelo, jSeleccionarMaterialTecho, jSeleccionarMaterialSuelo, jCostosAdicionales));
            jResultado.setText(String.valueOf(resultado)+" Bs.");
        }catch (NumberFormatException excepcion){
            jError.setText("¡Error! Los costos adicionales sólo pueden ser numeros");
        }catch (ArrayIndexOutOfBoundsException excepcion2){
            jError.setText(excepcion2.getLocalizedMessage());
        }
    }//GEN-LAST:event_jCalcularPresupuestoActionPerformed

    private void jTableMaterialesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMaterialesMousePressed
        
        pestanas.setSelectedIndex(4);
        
        //Numero de columna a la que le dieron click/INDICE DEL OBJETO EN EL ARRAYLIST
        int location=jTableMateriales.getSelectedRow();
        
        // Mostrar las opciones actuales de la pregunta anterior
        lErrorMat.setText("");
        jNombre.setText(modelo.globalAccess.listaDeMateriales.get(location).getNombre());
        jCostoVolumen.setText(String.valueOf(modelo.globalAccess.listaDeMateriales.get(location).getCostoporvolumen()));
        jCostoArea.setText(String.valueOf(modelo.globalAccess.listaDeMateriales.get(location).getCostoporarea()));
        
        Borrar.setVisible(true);
        //para indicarle que estamos editando una pregunta que ya existe
        editingCheck.setSelected(true); 
    }//GEN-LAST:event_jTableMaterialesMousePressed

    private void jButtonAgregarMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarMaterialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarMaterialMouseClicked

    private void jButtonAgregarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMaterialActionPerformed
        jNombre.setText("");
        jCostoVolumen.setText("");
        jCostoArea.setText("");
        lErrorMat.setText("");
        Borrar.setVisible(false);
        pestanas.setSelectedIndex(4);
        editingCheck.setSelected(false);
    }//GEN-LAST:event_jButtonAgregarMaterialActionPerformed

    private void jBuscadorDeMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscadorDeMatMouseClicked
        jBuscadorDeMat.setText("");
    }//GEN-LAST:event_jBuscadorDeMatMouseClicked

    private void jBuscadorDeMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscadorDeMatActionPerformed
        
    }//GEN-LAST:event_jBuscadorDeMatActionPerformed

    private void jBuscadorDeMatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscadorDeMatKeyReleased
        // Filtrado de objetos en la lista que contienen la letra en cuestion
        boolean option = true;
        String texto = jBuscadorDeMat.getText();
        
        
        jTableMateriales.setModel(controladora.vistaManagement.setModeloTablaMateriales(option,texto));
        JTableHeader tableHeader = jTableMateriales.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);


        jTableMateriales.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableMateriales.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableMateriales.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableMateriales.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableMateriales.setAutoResizeMode(jTableMateriales.AUTO_RESIZE_LAST_COLUMN);
        jTableMateriales.setRowHeight(20);
        jScrollPaneMateriales.setVisible(true);
        jTableMateriales.setVisible(true);


        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTableMateriales.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
    }//GEN-LAST:event_jBuscadorDeMatKeyReleased

    private void jNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreActionPerformed

    private void jCostoAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCostoAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCostoAreaActionPerformed

    private void jCostoVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCostoVolumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCostoVolumenActionPerformed

    private void volverMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_volverMatMouseClicked

    private void volverMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverMatActionPerformed
        // Limpiar todas las casillas de texto
        jNombre.setText("");
        jCostoVolumen.setText("");
        jCostoArea.setText("");
        lErrorMat.setText("");
        //pestanas.setSelectedIndex(1);
        menu2MouseClicked(null);
    }//GEN-LAST:event_volverMatActionPerformed

    private void guardarCambiosMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarCambiosMatMouseClicked
        // GUARDAR CAMBIOS
        double costoporvolumen, costoporarea;
        String nombre = "";
        ListaManagement vMan = new ListaManagement();
       
        if(jNombre.getText().isBlank() || jCostoVolumen.getText().isBlank() || jCostoArea.getText().isBlank()){
            lError.setText("Se deben rellenar todos los campos antes de guardar.");
            return;
        }
        // GUARDAR CAMBIOS EN VARIABLES
        try{
            nombre = jNombre.getText();
            costoporvolumen = Double.valueOf(jCostoVolumen.getText());
            costoporarea = Double.valueOf(jCostoArea.getText());
        }catch (NumberFormatException excepcion){
            lErrorMat.setText("¡Error! Los costos deben ser valores numéricos");
            return;
        }
        // GUARDANDO MATERIAL DEPENDIENDO DE SI ES EDICION O NO
        if(!editingCheck.isSelected()){
            // AGREGANDO NUEVO MATERIAL
            Material mat  = new Material(costoporvolumen,costoporarea,nombre);
            vMan.AddMaterial(mat);
        }else{
            // EDITANDO PREGUNTA
            int location=jTableMateriales.getSelectedRow();
            modelo.globalAccess.listaDeMateriales.get(location).setCostoporvolumen(costoporvolumen);
            modelo.globalAccess.listaDeMateriales.get(location).setCostoporarea(costoporarea);
            modelo.globalAccess.listaDeMateriales.get(location).setNombre(nombre);               
        }
        vMan.guardarMaterial();
        // RESETEAR LOS TEXTOS Y OPCIONES
        jNombre.setText("");
        jCostoVolumen.setText("");
        jCostoArea.setText("");
        lErrorMat.setText("");
        // VOLVER AL CUADRO
        //pestanas.setSelectedIndex(1);
        
        menu2MouseClicked(null);
    }//GEN-LAST:event_guardarCambiosMatMouseClicked

    private void guardarCambiosMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarCambiosMatActionPerformed

    private void jTabEditarMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabEditarMaterialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabEditarMaterialMouseClicked

    private void jScrollPaneMaterialesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPaneMaterialesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPaneMaterialesMousePressed

    private void jNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNombreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreMouseEntered

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int location=jTablePreguntas.getSelectedRow();
        ListaManagement vMan = new ListaManagement();
        modelo.globalAccess.listaDePreguntas.remove(location);
        vMan.guardarPregunta();
        menu1MouseClicked(null);
    }//GEN-LAST:event_EliminarActionPerformed

    private void BorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarMouseClicked

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        int location=jTableMateriales.getSelectedRow();
        ListaManagement vMan = new ListaManagement();
        modelo.globalAccess.listaDeMateriales.remove(location);
        vMan.guardarMaterial();
        menu2MouseClicked(null);
    }//GEN-LAST:event_BorrarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jBotonDeBuscarMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotonDeBuscarMatMouseClicked
        // Filtrado de objetos en la lista que contienen la letra en cuestion
        boolean option = true;
        String texto = jBuscadorDeMat.getText();
        
        
        jTableMateriales.setModel(controladora.vistaManagement.setModeloTablaMateriales(option,texto));
        JTableHeader tableHeader = jTableMateriales.getTableHeader();
        Font headerFont = new Font("Arial", Font.BOLD, 18);
        float[] hsbColor = new float[3];
        Color.RGBtoHSB(163, 58, 0, hsbColor);
        tableHeader.setForeground(Color.getHSBColor(hsbColor[0],hsbColor[1],hsbColor[2]));
        tableHeader.setFont(headerFont);


        jTableMateriales.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableMateriales.getColumnModel().getColumn(1).setPreferredWidth(600);
        jTableMateriales.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableMateriales.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableMateriales.setAutoResizeMode(jTableMateriales.AUTO_RESIZE_LAST_COLUMN);
        jTableMateriales.setRowHeight(20);
        jScrollPaneMateriales.setVisible(true);
        jTableMateriales.setVisible(true);


        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTableMateriales.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
    }//GEN-LAST:event_jBotonDeBuscarMatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Background1;
    private javax.swing.JPanel Banner;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Opcion1;
    private javax.swing.JTextField Opcion2;
    private javax.swing.JTextField Opcion3;
    private javax.swing.JTextField Opcion4;
    private javax.swing.JTextField Pregunta;
    private javax.swing.ButtonGroup buttonGroupOpcionCorrecta;
    private javax.swing.JButton cargarImagen;
    private javax.swing.JCheckBox editingCheck;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JButton guardarCambiosMat;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jBotonDeBuscar;
    private javax.swing.JPanel jBotonDeBuscarMat;
    private javax.swing.JTextField jBuscadorDeMat;
    private javax.swing.JTextField jBuscadorDePreg;
    private javax.swing.JButton jButtonAgregarMaterial;
    private javax.swing.JButton jButtonAgregarPregunta;
    private javax.swing.JButton jButtonAgregarPregunta1;
    private javax.swing.JButton jCalcularPresupuesto;
    private javax.swing.JTextField jCostoArea;
    private javax.swing.JTextField jCostoVolumen;
    private javax.swing.JTextField jCostosAdicionales;
    private javax.swing.JLabel jError;
    private javax.swing.JLabel jInstruccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPaneFondo;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanelButtonGuide;
    private javax.swing.JPanel jPanelButtonGuide1;
    private javax.swing.JPanel jPanelGuide;
    private javax.swing.JPanel jPanelGuide1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel jResultado;
    private javax.swing.JPanel jResultadoPan;
    private javax.swing.JScrollPane jScrollPaneMateriales;
    private javax.swing.JScrollPane jScrollPanePreguntas;
    private javax.swing.JComboBox<String> jSeleccionarMaterialParedes;
    private javax.swing.JComboBox<String> jSeleccionarMaterialSuelo;
    private javax.swing.JComboBox<String> jSeleccionarMaterialTecho;
    private javax.swing.JPanel jTabEditarMaterial;
    private javax.swing.JPanel jTabEditarPregunta;
    private javax.swing.JPanel jTabMateriales;
    private javax.swing.JPanel jTabPreguntas;
    private javax.swing.JPanel jTabPresupuesto;
    private javax.swing.JTable jTableMateriales;
    private javax.swing.JTable jTablePreguntas;
    private javax.swing.JLabel lError;
    private javax.swing.JLabel lErrorMat;
    private javax.swing.JLabel materiales;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JTabbedPane pestanas;
    private javax.swing.JLabel preguntas;
    private javax.swing.JLabel presupuesto;
    private javax.swing.JButton volver;
    private javax.swing.JButton volverMat;
    // End of variables declaration//GEN-END:variables
}
