/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Edixon Gonzalez
 */
public class Resultadov2 extends javax.swing.JFrame {

    
    public Resultadov2(int pJ1,int pJ2, int modoDeJuego) {
        initComponents();
        labelPuntuacionJugador1.setText(String.valueOf(pJ1));
        labelPuntuacionJugador2.setText(String.valueOf(pJ2));
        if (modoDeJuego==1) {
            labelJugador2.setVisible(false);
            labelPuntuacionJugador2.setVisible(false);
        }
        if(pJ1==pJ2){
            labelGanador.setText("EMPATE!!!");     
        }else{
            if(pJ1>pJ2){
                labelGanador.setText("GANÓ El JUGADOR 1!!!!");     
            }else{
                labelGanador.setText("GANÓ El JUGADOR 2!!!!");     
            }
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        labelNombrePagina = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelJugador1 = new javax.swing.JLabel();
        labelPuntuacionJugador1 = new javax.swing.JLabel();
        labelPuntuacionJugador2 = new javax.swing.JLabel();
        labelJugador2 = new javax.swing.JLabel();
        panelGanador = new javax.swing.JPanel();
        labelGanador = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnVolverInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setBackground(new java.awt.Color(176, 176, 176));
        Banner.setPreferredSize(new java.awt.Dimension(1280, 100));

        labelNombrePagina.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelNombrePagina.setForeground(new java.awt.Color(255, 255, 255));
        labelNombrePagina.setText("CABINAS AZULES");

        labelResultado.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(255, 255, 255));
        labelResultado.setText("Resultado");

        javax.swing.GroupLayout BannerLayout = new javax.swing.GroupLayout(Banner);
        Banner.setLayout(BannerLayout);
        BannerLayout.setHorizontalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BannerLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombrePagina, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        BannerLayout.setVerticalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BannerLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(labelNombrePagina, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        panelFondo.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelJugador1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelJugador1.setText("JUGADOR 1");

        labelPuntuacionJugador1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelPuntuacionJugador1.setText("PUNTUACION");

        labelPuntuacionJugador2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelPuntuacionJugador2.setText("PUNTUACION");

        labelJugador2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelJugador2.setText("JUGADOR 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJugador1)
                    .addComponent(labelJugador2))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPuntuacionJugador2)
                    .addComponent(labelPuntuacionJugador1))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJugador1)
                    .addComponent(labelPuntuacionJugador1))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJugador2)
                    .addComponent(labelPuntuacionJugador2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 620, 160));

        panelGanador.setBackground(new java.awt.Color(102, 102, 255));

        labelGanador.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGanador.setText("GANÓ El JUGADOR 1/2!!!!");

        javax.swing.GroupLayout panelGanadorLayout = new javax.swing.GroupLayout(panelGanador);
        panelGanador.setLayout(panelGanadorLayout);
        panelGanadorLayout.setHorizontalGroup(
            panelGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGanadorLayout.createSequentialGroup()
                .addComponent(labelGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        panelGanadorLayout.setVerticalGroup(
            panelGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGanadorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelGanador)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        panelFondo.add(panelGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1060, 150));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        btnVolverInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolverInicio.setText("Volver");
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(btnVolverInicio)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnVolverInicio)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelFondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1060, 70));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        this.dispose();
        controladora.vistaManagement.loadStart();
    }//GEN-LAST:event_btnVolverInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelGanador;
    private javax.swing.JLabel labelJugador1;
    private javax.swing.JLabel labelJugador2;
    private javax.swing.JLabel labelNombrePagina;
    private javax.swing.JLabel labelPuntuacionJugador1;
    private javax.swing.JLabel labelPuntuacionJugador2;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelGanador;
    // End of variables declaration//GEN-END:variables
}
