/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Edixon Gonzalez
 */
public class Resultadov2 extends javax.swing.JFrame {

    
    public Resultadov2(int pJ1,int pJ2, int modoDeJuego) {
        initComponents();
        labelPuntuacionJugador1.setText(String.valueOf(pJ1));
        labelPuntuacionJugador2.setText(String.valueOf(pJ2));
        if (modoDeJuego==1) {
            labelJugador2.setVisible(false);
            labelPuntuacionJugador2.setVisible(false);
        }
        if(pJ1==pJ2){
            labelGanador.setText("EMPATE!!!");     
        }else{
            if(pJ1>pJ2){
                labelGanador.setText("GANÓ El JUGADOR 1!!!!");     
            }else{
                labelGanador.setText("GANÓ El JUGADOR 2!!!!");     
            }
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        labelNombrePagina = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelJugador1 = new javax.swing.JLabel();
        labelPuntuacionJugador1 = new javax.swing.JLabel();
        labelPuntuacionJugador2 = new javax.swing.JLabel();
        labelJugador2 = new javax.swing.JLabel();
        panelGanador = new javax.swing.JPanel();
        labelGanador = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnVolverInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(255, 242, 223));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setBackground(new java.awt.Color(78, 95, 23));
        Banner.setPreferredSize(new java.awt.Dimension(1280, 100));
        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombrePagina.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelNombrePagina.setForeground(new java.awt.Color(213, 223, 181));
        labelNombrePagina.setText("CABINAS AZULES");
        Banner.add(labelNombrePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 436, 36));

        labelResultado.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(213, 223, 181));
        labelResultado.setText("Resultado");
        Banner.add(labelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 436, 36));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/glasses.png"))); // NOI18N
        Banner.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        panelFondo.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 140));

        jPanel2.setBackground(new java.awt.Color(255, 242, 223));

        labelJugador1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelJugador1.setForeground(new java.awt.Color(123, 58, 0));
        labelJugador1.setText("JUGADOR 1");

        labelPuntuacionJugador1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelPuntuacionJugador1.setForeground(new java.awt.Color(123, 58, 0));
        labelPuntuacionJugador1.setText("PUNTUACION");

        labelPuntuacionJugador2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelPuntuacionJugador2.setForeground(new java.awt.Color(123, 58, 0));
        labelPuntuacionJugador2.setText("PUNTUACION");

        labelJugador2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelJugador2.setForeground(new java.awt.Color(123, 58, 0));
        labelJugador2.setText("JUGADOR 2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJugador1)
                    .addComponent(labelJugador2))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPuntuacionJugador2)
                    .addComponent(labelPuntuacionJugador1))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJugador1)
                    .addComponent(labelPuntuacionJugador1))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJugador2)
                    .addComponent(labelPuntuacionJugador2))
                .addGap(30, 30, 30))
        );

        panelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 620, 160));

        panelGanador.setBackground(new java.awt.Color(102, 102, 255));

        labelGanador.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        labelGanador.setForeground(new java.awt.Color(255, 255, 255));
        labelGanador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGanador.setText("GANÓ El JUGADOR 1/2!!!!");

        javax.swing.GroupLayout panelGanadorLayout = new javax.swing.GroupLayout(panelGanador);
        panelGanador.setLayout(panelGanadorLayout);
        panelGanadorLayout.setHorizontalGroup(
            panelGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGanadorLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(labelGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGanadorLayout.setVerticalGroup(
            panelGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGanadorLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(labelGanador)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panelFondo.add(panelGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 1060, 130));

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        btnVolverInicio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVolverInicio.setForeground(new java.awt.Color(123, 58, 0));
        btnVolverInicio.setText("Volver");
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(460, Short.MAX_VALUE)
                .addComponent(btnVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(434, 434, 434))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(btnVolverInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        panelFondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 1060, 100));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        this.dispose();
        controladora.vistaManagement.loadStart();
    }//GEN-LAST:event_btnVolverInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelGanador;
    private javax.swing.JLabel labelJugador1;
    private javax.swing.JLabel labelJugador2;
    private javax.swing.JLabel labelNombrePagina;
    private javax.swing.JLabel labelPuntuacionJugador1;
    private javax.swing.JLabel labelPuntuacionJugador2;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelGanador;
    // End of variables declaration//GEN-END:variables
}
