/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.util.List;
import modelo.Pregunta;
import controladora.ListaManagement;
/**
 *
 * @author Edixon Gonzalez
 */
public class vistaJuegoPreguntas extends javax.swing.JFrame {
    private int lPreguntas[];
    private int pJ1 = 0;
    private int pJ2 = 0;
    private int ipregunta=0;
    private modelo.Pregunta pActual;
    ListaManagement lManagement = new ListaManagement(); 
    /**
     * Creates new form vistaJuegoPreguntas
     */
    public int modoDeJuego;
    //private static int modoDeJuego;
    
    public vistaJuegoPreguntas() {
        initComponents();
    }
    
    public vistaJuegoPreguntas(int jugadores, int lPreg[]) {
        lPreguntas = lPreg;
        initComponents();
        loadPregunta(lManagement.getPregunta(lPreguntas[ipregunta]));
        setModoDeJuego(jugadores);
    }
    public void setModoDeJuego(int jugadores){
        modoDeJuego = jugadores;
        
        if (modoDeJuego==1){
            pnlTurnoJugador.setVisible(false);
        }
    }
    public void loadNextPregunta(){
        ipregunta++;
        if((ipregunta%modoDeJuego)==0){
            lblTurnoJugadores.setText("Jugador 1, ¡es tu turno!");
        }else{
            lblTurnoJugadores.setText("Jugador 2, ¡es tu turno!");
        }
        
        if(ipregunta<lPreguntas.length){
            loadPregunta(lManagement.getPregunta(lPreguntas[ipregunta]));
        }else{
            this.dispose();
            lManagement.guardarPregunta();
            controladora.vistaManagement.loadResultado(pJ1,pJ2,modoDeJuego);
        }
    }
    public void loadPregunta(Pregunta vP){
        jPregunta.setText(vP.getEnunciado());
        taOpcionA.setText(vP.getOpciones()[0]);
        taOpcionB.setText(vP.getOpciones()[1]);
        taOpcionC.setText(vP.getOpciones()[2]);
        taOpcionD.setText(vP.getOpciones()[3]);
        pActual= vP;       
    }
    public void respuestaDefinitiva(int vOpcion){
        if(pActual.getRespuestacorrecta()==vOpcion){
            pActual.setAciertos(pActual.getAciertos()+1);
            if((ipregunta%modoDeJuego)==0){
                pJ1++;
            }else{
                pJ2++; 
            }
        }
        pActual.setUsos(pActual.getUsos()+1);
        loadNextPregunta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        Banner = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        btnVolverInicio = new javax.swing.JLabel();
        pnlTurnoJugador = new javax.swing.JPanel();
        lblTurnoJugadores = new javax.swing.JLabel();
        jOpcionA = new javax.swing.JPanel();
        taOpcionA = new javax.swing.JTextArea();
        jOpcionB = new javax.swing.JPanel();
        taOpcionB = new javax.swing.JTextArea();
        jOpcionC = new javax.swing.JPanel();
        taOpcionC = new javax.swing.JTextArea();
        jOpcionD = new javax.swing.JPanel();
        taOpcionD = new javax.swing.JTextArea();
        jImagen1 = new javax.swing.JPanel();
        jImagen2 = new javax.swing.JPanel();
        jPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(255, 242, 223));
        jFondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Banner.setBackground(new java.awt.Color(78, 95, 23));
        Banner.setPreferredSize(new java.awt.Dimension(1280, 160));
        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(213, 223, 181));
        jLabel5.setText("CABINAS AZULES");
        Banner.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 436, 36));

        jLabel14.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(213, 223, 181));
        jLabel14.setText("¡Bienvenidos al quiz!");
        Banner.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 436, 36));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/glasses.png"))); // NOI18N
        Banner.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnVolverInicio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnVolverInicio.setForeground(new java.awt.Color(242, 242, 242));
        btnVolverInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logout.png"))); // NOI18N
        btnVolverInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverInicioMouseClicked(evt);
            }
        });
        Banner.add(btnVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 50, -1, -1));

        jFondo.add(Banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlTurnoJugador.setBackground(new java.awt.Color(78, 95, 23));

        lblTurnoJugadores.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        lblTurnoJugadores.setForeground(new java.awt.Color(213, 223, 181));
        lblTurnoJugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTurnoJugadores.setText("Jugador 1, ¡es tu turno!");

        javax.swing.GroupLayout pnlTurnoJugadorLayout = new javax.swing.GroupLayout(pnlTurnoJugador);
        pnlTurnoJugador.setLayout(pnlTurnoJugadorLayout);
        pnlTurnoJugadorLayout.setHorizontalGroup(
            pnlTurnoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTurnoJugadorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTurnoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlTurnoJugadorLayout.setVerticalGroup(
            pnlTurnoJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTurnoJugadorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTurnoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jFondo.add(pnlTurnoJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 440, 70));

        jOpcionA.setBackground(new java.awt.Color(255, 87, 87));

        taOpcionA.setEditable(false);
        taOpcionA.setBackground(new java.awt.Color(255, 87, 87));
        taOpcionA.setColumns(20);
        taOpcionA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taOpcionA.setLineWrap(true);
        taOpcionA.setRows(5);
        taOpcionA.setWrapStyleWord(true);
        taOpcionA.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        taOpcionA.setEnabled(false);
        taOpcionA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taOpcionAMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jOpcionALayout = new javax.swing.GroupLayout(jOpcionA);
        jOpcionA.setLayout(jOpcionALayout);
        jOpcionALayout.setHorizontalGroup(
            jOpcionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taOpcionA)
                .addContainerGap())
        );
        jOpcionALayout.setVerticalGroup(
            jOpcionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taOpcionA, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFondo.add(jOpcionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 510, 100));

        jOpcionB.setBackground(new java.awt.Color(140, 82, 255));
        jOpcionB.setPreferredSize(new java.awt.Dimension(510, 92));

        taOpcionB.setEditable(false);
        taOpcionB.setBackground(new java.awt.Color(140, 82, 255));
        taOpcionB.setColumns(20);
        taOpcionB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taOpcionB.setLineWrap(true);
        taOpcionB.setRows(5);
        taOpcionB.setWrapStyleWord(true);
        taOpcionB.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        taOpcionB.setEnabled(false);
        taOpcionB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taOpcionBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jOpcionBLayout = new javax.swing.GroupLayout(jOpcionB);
        jOpcionB.setLayout(jOpcionBLayout);
        jOpcionBLayout.setHorizontalGroup(
            jOpcionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taOpcionB)
                .addContainerGap())
        );
        jOpcionBLayout.setVerticalGroup(
            jOpcionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jOpcionBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(taOpcionB, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFondo.add(jOpcionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, 100));

        jOpcionC.setBackground(new java.awt.Color(126, 217, 87));
        jOpcionC.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        taOpcionC.setEditable(false);
        taOpcionC.setBackground(new java.awt.Color(126, 217, 87));
        taOpcionC.setColumns(20);
        taOpcionC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taOpcionC.setLineWrap(true);
        taOpcionC.setRows(5);
        taOpcionC.setWrapStyleWord(true);
        taOpcionC.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        taOpcionC.setEnabled(false);
        taOpcionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taOpcionCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jOpcionCLayout = new javax.swing.GroupLayout(jOpcionC);
        jOpcionC.setLayout(jOpcionCLayout);
        jOpcionCLayout.setHorizontalGroup(
            jOpcionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taOpcionC)
                .addContainerGap())
        );
        jOpcionCLayout.setVerticalGroup(
            jOpcionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taOpcionC, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        jFondo.add(jOpcionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 510, 100));

        jOpcionD.setBackground(new java.awt.Color(255, 189, 89));
        jOpcionD.setPreferredSize(new java.awt.Dimension(510, 92));

        taOpcionD.setEditable(false);
        taOpcionD.setBackground(new java.awt.Color(255, 189, 89));
        taOpcionD.setColumns(20);
        taOpcionD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taOpcionD.setLineWrap(true);
        taOpcionD.setRows(5);
        taOpcionD.setWrapStyleWord(true);
        taOpcionD.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        taOpcionD.setEnabled(false);
        taOpcionD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taOpcionDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jOpcionDLayout = new javax.swing.GroupLayout(jOpcionD);
        jOpcionD.setLayout(jOpcionDLayout);
        jOpcionDLayout.setHorizontalGroup(
            jOpcionDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taOpcionD)
                .addContainerGap())
        );
        jOpcionDLayout.setVerticalGroup(
            jOpcionDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jOpcionDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taOpcionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFondo.add(jOpcionD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, 100));

        jImagen1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jImagen1Layout = new javax.swing.GroupLayout(jImagen1);
        jImagen1.setLayout(jImagen1Layout);
        jImagen1Layout.setHorizontalGroup(
            jImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        jImagen1Layout.setVerticalGroup(
            jImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jFondo.add(jImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 230));

        jImagen2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jImagen2Layout = new javax.swing.GroupLayout(jImagen2);
        jImagen2.setLayout(jImagen2Layout);
        jImagen2Layout.setHorizontalGroup(
            jImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        jImagen2Layout.setVerticalGroup(
            jImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jFondo.add(jImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, -1, 230));

        jPregunta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPregunta.setForeground(new java.awt.Color(123, 58, 0));
        jPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPregunta.setText("Pregunta sacada de la base de datos");
        jFondo.add(jPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 660, 88));

        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverInicioMouseClicked
        this.dispose();
        controladora.vistaManagement.loadStart();
    }//GEN-LAST:event_btnVolverInicioMouseClicked

    private void taOpcionAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taOpcionAMouseClicked
        respuestaDefinitiva(1);
    }//GEN-LAST:event_taOpcionAMouseClicked

    private void taOpcionBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taOpcionBMouseClicked
        respuestaDefinitiva(2);
    }//GEN-LAST:event_taOpcionBMouseClicked

    private void taOpcionCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taOpcionCMouseClicked
        respuestaDefinitiva(3);
    }//GEN-LAST:event_taOpcionCMouseClicked

    private void taOpcionDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taOpcionDMouseClicked
        respuestaDefinitiva(4);
    }//GEN-LAST:event_taOpcionDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaJuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaJuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaJuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaJuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaJuegoPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JLabel btnVolverInicio;
    private javax.swing.JPanel jFondo;
    private javax.swing.JPanel jImagen1;
    private javax.swing.JPanel jImagen2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jOpcionA;
    private javax.swing.JPanel jOpcionB;
    private javax.swing.JPanel jOpcionC;
    private javax.swing.JPanel jOpcionD;
    private javax.swing.JLabel jPregunta;
    private javax.swing.JLabel lblTurnoJugadores;
    private javax.swing.JPanel pnlTurnoJugador;
    private javax.swing.JTextArea taOpcionA;
    private javax.swing.JTextArea taOpcionB;
    private javax.swing.JTextArea taOpcionC;
    private javax.swing.JTextArea taOpcionD;
    // End of variables declaration//GEN-END:variables
}
